### ISSUE TITLE
io.etcd.jetcd.shaded.io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!

### ISSUE THREAD

**Issue by carlye** [etcd-io/jetcd#1008]
After running for a period of time, our application reports “io.etcd.jetcd.shaded.io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!” . Back to normal after restart the application. I guess there may be a problem with the channel .
How can we fix it ?  Any suggestions are greatly appreciated !

        <dependency>
            <groupId>io.etcd</groupId>
            <artifactId>jetcd-core</artifactId>
            <version>0.5.0</version>
        </dependency>

**Comment by carlye** [comment]
2021-11-05 00:02:12 |-ERROR in c.i.v.c.c.e.EtcdClient at [EtcdClient.java:242] - Read ETCD[uap-mock-dev.properties],Error：java.util.concurrent.ExecutionException: i
o.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at net.jodah.failsafe.FailsafeFuture.completeResult(FailsafeFuture.java:90)
        at net.jodah.failsafe.AsyncExecution.complete(AsyncExecution.java:216)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at net.jodah.failsafe.Functions.lambda$null$2(Functions.java:101)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
        at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)
        at net.jodah.failsafe.Functions.lambda$null$3(Functions.java:97)
        at net.jodah.failsafe.internal.util.DelegatingScheduler.lambda$schedule$0(DelegatingScheduler.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:553)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:534)
        at io.etcd.jetcd.ClientConnectionManager.lambda$execute$4(ClientConnectionManager.java:331)
        at net.jodah.failsafe.Functions.lambda$toCtxSupplier$15(Functions.java:268)
        at net.jodah.failsafe.Functions.lambda$getPromise$1(Functions.java:80)
        at net.jodah.failsafe.RetryPolicyExecutor$1.call(RetryPolicyExecutor.java:101)
        at net.jodah.failsafe.RetryPolicyExecutor.lambda$supplyAsync$1(RetryPolicyExecutor.java:139)
        ... 6 common frames omitted
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:497)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.etcd.jetcd.ClientConnectionManager$AuthTokenInterceptor$1$1.onClose(ClientConnectionManager.java:289)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        ... 3 common frames omitted
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:717)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)

**Comment by lburgazzoli** [comment]
The cause is `java.lang.OutOfMemoryError: unable to create new native thread` so it may be that there is some memory leak somewhere (either in jetcd or in your code).

You need to profile the application to see what's the root cause or provide a reproducer and I'll investigate.

**Comment by carlye** [comment]
Thank you very much for your reply, we will carefully check the code again.  When we reproduce or find a problem, we will contact you again
