### ISSUE TITLE
Server side will close connection automatically when client watch many keys? 

### ISSUE THREAD

**Issue by horizonzy** [etcd-io/jetcd#1039]
**Versions**
- etcd: 3.4.7
- jetcd: 0.4.1
- java: jdk8

**Describe the bug**
In my situation, my client will get key value and watch it,  the number of key about 20w. 
When the programer running, the key number reach abount 10w, the exception happened. 
It looks the connection be closed by server side. At the same time, observer the netstat, the connection closed, then establish a new connection.

![image](https://user-images.githubusercontent.com/22524871/146924773-b816c722-ba27-4f74-a943-1d62ac295916.png)

**To Reproduce**
get key value and watch it, the number about 20w.

**Additional context**
The error log from watch error.
```
io.etcd.jetcd.common.exception.EtcdException: io exception
        at io.etcd.jetcd.common.exception.EtcdExceptionFactory.newEtcdException(EtcdExceptionFactory.java:34)
        at io.etcd.jetcd.common.exception.EtcdExceptionFactory.fromStatus(EtcdExceptionFactory.java:86)
        at io.etcd.jetcd.common.exception.EtcdExceptionFactory.toEtcdException(EtcdExceptionFactory.java:82)
        at io.etcd.jetcd.WatchImpl$WatcherImpl.onError(WatchImpl.java:263)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.etcd.jetcd.ClientConnectionManager$AuthTokenInterceptor$1$1.onClose(ClientConnectionManager.java:311)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
```

**Comment by lburgazzoli** [comment]
At the moment the watch impl is a little inefficient as it creates a watcher per watch, int eh future this need to be improved by re-using the same channel.

Out of curiosity, why do you need to create so many watchers ? can't you watch using i.e. a prefix ?

**Comment by horizonzy** [comment]
> Out of curiosity, why do you need to create so many watchers ? can't you watch using i.e. a prefix ?

Is there some differentce between `multi key watch` and `prefix watch`. `prefix watch` is less performance loss than `multi key watch`

**Comment by lburgazzoli** [comment]
For a prefix watch you do a single watch request and then you get all the events on the relevant keys it certainly reduce the resource both the server and the client require

**Comment by horizonzy** [comment]
> For a prefix watch you do a single watch request and then you get all the events on the relevant keys it certainly reduce the resource both the server and the client require

Thanks, I will modify the way of watch
