### ISSUE TITLE
jetcd 0.5.11 giving error when calling KVClient.Get() method

### ISSUE THREAD

**Issue by mster429** [etcd-io/jetcd#1045]
I have wriiten a jetcd client wrapper in a spring application. And it uses jetcd-core 0.5.11. Getting following error while fetching the config value via KVClient.

Wrapper Method
```
    public ByteSequence Get(String key) throws EtcdException {
        GetResponse response = null;
        try {
            CompletableFuture<GetResponse> getFuture = EtcdClient.get(ByteSequence.from(key, StandardCharsets.UTF_8));
            response = getFuture.get();
            if (response.getKvs().isEmpty()) {
                logger.error(String.format("Empty KeyValues returned for key: %s\n", key));
                return null;
            }
            return response.getKvs().get(0).getValue();
        } catch (Exception e) {
            throw new EtcdException(new EtcdError("Error in Etcd Client GET"), e.getMessage());
        }
    }
```

```
java.lang.NoSuchMethodError: 'void io.netty.buffer.PooledByteBufAllocator.<init>(boolean, int, int, int, int, int, int, boolean)'
        at io.grpc.netty.Utils.createByteBufAllocator(Utils.java:176) ~[grpc-netty-1.42.1.jar!/:1.42.1]
        at io.grpc.netty.Utils.access$000(Utils.java:75) ~[grpc-netty-1.42.1.jar!/:1.42.1]
        at io.grpc.netty.Utils$ByteBufAllocatorPreferDirectHolder.<clinit>(Utils.java:97) ~[grpc-netty-1.42.1.jar!/:1.42.1]
        at io.grpc.netty.Utils.getByteBufAllocator(Utils.java:144) ~[grpc-netty-1.42.1.jar!/:1.42.1]
        at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:233) ~[grpc-netty-1.42.1.jar!/:1.42.1]
        at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34) ~[grpc-core-1.42.1.jar!/:1.42.1]
        at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34) ~[grpc-core-1.42.1.jar!/:1.42.1]
        at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:259) ~[grpc-core-1.42.1.jar!/:1.42.1]
        at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:66) ~[grpc-core-1.42.1.jar!/:1.42.1]
        at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:201) ~[grpc-core-1.42.1.jar!/:1.42.1]
        at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95) ~[grpc-api-1.42.1.jar!/:1.42.1]
        at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127) ~[grpc-api-1.42.1.jar!/:1.42.1]
        at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1872) ~[grpc-core-1.42.1.jar!/:1.42.1]
        at io.grpc.NameResolver$Listener2.onAddresses(NameResolver.java:210) ~[grpc-api-1.42.1.jar!/:1.42.1]
        at io.etcd.jetcd.resolver.AbstractNameResolver.doResolve(AbstractNameResolver.java:127) ~[jetcd-core-0.6.0.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na] 

org.pickme.etcd.client.EtcdException: io.etcd.jetcd.common.exception.EtcdException: Panic! This is a bug!
```

**Comment by Jon-Gaara** [comment]
This may be caused by the grpc version，you can use jetcd-all instead of jetcd-core or change the jetcd core version to 0.5.0.

**Comment by lburgazzoli** [comment]
note that jetcd-all is not more provided starting from jetcd 0.6.x
