### ISSUE TITLE
The vertx instance is not closed when closing ClientConnectionManager

### ISSUE THREAD

**Issue by Apache9** [etcd-io/jetcd#1063]
**Versions**
- etcd: not important
- jetcd: 0.7.0
- java: not important

**Describe the bug**
When connecting to etcd, we will intialize a vertx instance. But in ClientConnectionManager.defaultChannelBuilder, we just store the vertx instance to a local variable so when closing ClientConnectionManager, we have no way to close the vertx instance. It will create a non daemon thread by default which causes the process to hang.

**To Reproduce**
```
    public static void main(String[] args) {
        NameResolverRegistry.getDefaultRegistry().register(new IPResolverProvider());
        Client c = Client.builder().endpoints("http://localhost:2380").build();
        try {
            // not important, just want to initialize vertx
            c.getKVClient().get(ByteSequence.from("/whatever", StandardCharsets.UTF_8)).get();
        } catch (Exception e) {
            e.printStackTrace();
        }
        c.close();
        // the process will hang there forever
    }
```

**Expected behavior**
The process should quit normally after we close the Client.

**Additional context**
The jstack result of the above code sniff
```
"vertx-blocked-thread-checker" #15 daemon prio=5 os_prio=0 cpu=1.67ms elapsed=8.09s tid=0x00007fd708bbe000 nid=0x2515b in Object.wait()  [0x00007fd6ccc42000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.14/Native Method)
	- waiting on <0x00000006a047b678> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(java.base@11.0.14/Timer.java:553)
	- waiting to re-lock in wait() <0x00000006a047b678> (a java.util.TaskQueue)
	at java.util.TimerThread.run(java.base@11.0.14/Timer.java:506)

"vert.x-eventloop-thread-0" #17 prio=5 os_prio=0 cpu=82.00ms elapsed=7.90s tid=0x00007fd66c03d000 nid=0x2515d runnable  [0x00007fd6cc640000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@11.0.14/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.14/EPollSelectorImpl.java:120)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.14/SelectorImpl.java:124)
	- locked <0x00000006a01ed928> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006a01e27f8> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@11.0.14/SelectorImpl.java:141)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:813)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@11.0.14/Thread.java:829)
```

The vert.x-eventloop-thread-0 is the criminal which hang the process.

**Comment by lburgazzoli** [comment]
fixed by https://github.com/etcd-io/jetcd/pull/1064
