### ISSUE TITLE
0.7.1 GRPC   io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!

### ISSUE THREAD

**Issue by fifthangel** [etcd-io/jetcd#1073]
**Versions**
- etcd: 3.4.16
- jetcd: 0.7.1
- java:  jdk 1.8 ,spring boot 2.2.1.release

**Describe the bug**
 Etcd client cacth the  GRPC bug .

**To Reproduce**

Exception  here :
java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocator.<init>(ZIIIIIIZ)V
	at io.grpc.netty.Utils.createByteBufAllocator(Utils.java:176)
	at io.grpc.netty.Utils.access$000(Utils.java:75)
	at io.grpc.netty.Utils$ByteBufAllocatorPreferDirectHolder.<clinit>(Utils.java:97)
	at io.grpc.netty.Utils.getByteBufAllocator(Utils.java:144)
	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:233)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:259)
	at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:66)
	at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:201)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:1012)
	at io.etcd.jetcd.impl.ClientConnectionManager$1.interceptCall(ClientConnectionManager.java:222)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
	at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:923)
	at io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63)
	at io.etcd.jetcd.api.KVGrpc$KVStub.range(KVGrpc.java:343)
	at io.vertx.grpc.stub.ClientCalls.oneToOne(ClientCalls.java:41)
	at io.etcd.jetcd.api.VertxKVGrpc$KVVertxStub.range(VertxKVGrpc.java:48)
	at io.etcd.jetcd.impl.KVImpl.lambda$get$2(KVImpl.java:82)
	at io.etcd.jetcd.impl.Impl.lambda$execute$4(Impl.java:131)
	at net.jodah.failsafe.Functions.lambda$toCtxSupplier$15(Functions.java:298)
	at net.jodah.failsafe.Functions.lambda$getPromiseOfStage$7(Functions.java:174)
	at net.jodah.failsafe.Functions.lambda$null$3(Functions.java:107)
	at net.jodah.failsafe.internal.util.DelegatingScheduler.lambda$schedule$0(DelegatingScheduler.java:141)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

 syncclient||2022-06-29 15:23:56,996|ERROR|10000|22176|main|c.y.s.register.schedule.SyncApisJobTest.syncApis:95|>>>>>>>>>>> ex

java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at com.yxt.svcmaker.register.core.client.SingleDataSourceEtcdClient.getPrefix(SingleDataSourceEtcdClient.java:214)
	... 33 common frames omitted

Caused by: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at io.vertx.grpc.VertxChannelBuilder.lambda$build$1(VertxChannelBuilder.java:300)
	at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:102)
	at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:95)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closedInternal(ClientCallImpl.java:751)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:687)
	at io.grpc.internal.RetriableStream$Sublistener$5.run(RetriableStream.java:982)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.RetriableStream$Sublistener.closed(RetriableStream.java:977)
	at io.grpc.internal.FailingClientStream.start(FailingClientStream.java:61)
	at io.grpc.internal.RetriableStream$StartEntry.runWith(RetriableStream.java:349)
	at io.grpc.internal.RetriableStream.drain(RetriableStream.java:313)
	at io.grpc.internal.RetriableStream.start(RetriableStream.java:390)
	at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:289)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:191)
	at io.grpc.internal.DelayedClientCall.start(DelayedClientCall.java:179)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
	at io.etcd.jetcd.impl.ClientConnectionManager$1$1.start(ClientConnectionManager.java:226)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:341)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:315)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:303)
	at io.grpc.stub.ClientCalls.asyncUnaryCall(ClientCalls.java:76)
	at io.etcd.jetcd.api.KVGrpc$KVStub.range(KVGrpc.java:342)
	at io.vertx.grpc.stub.ClientCalls.oneToOne(ClientCalls.java:41)
	at io.etcd.jetcd.api.VertxKVGrpc$KVVertxStub.range(VertxKVGrpc.java:48)
	at io.etcd.jetcd.impl.KVImpl.lambda$get$2(KVImpl.java:82)
	at io.etcd.jetcd.impl.Impl.lambda$execute$4(Impl.java:131)
	at net.jodah.failsafe.Functions.lambda$toCtxSupplier$15(Functions.java:298)
	at net.jodah.failsafe.Functions.lambda$getPromiseOfStage$7(Functions.java:174)
	at net.jodah.failsafe.Functions.lambda$null$3(Functions.java:107)
	at net.jodah.failsafe.internal.util.DelegatingScheduler.lambda$schedule$0(DelegatingScheduler.java:141)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Caused by: java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocator.<init>(ZIIIIIIZ)V

	at io.grpc.netty.Utils.createByteBufAllocator(Utils.java:176)
	at io.grpc.netty.Utils.access$000(Utils.java:75)
	at io.grpc.netty.Utils$ByteBufAllocatorPreferDirectHolder.<clinit>(Utils.java:97)
	at io.grpc.netty.Utils.getByteBufAllocator(Utils.java:144)
	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:233)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:259)
	at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:66)
	at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:201)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:1012)
	at io.etcd.jetcd.impl.ClientConnectionManager$1.interceptCall(ClientConnectionManager.java:222)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
	at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:923)
	at io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63)
	at io.etcd.jetcd.api.KVGrpc$KVStub.range(KVGrpc.java:343)

**Expected behavior**
 Just run application, the exception throwed.

**Additional context**

**Comment by liangyuanpeng** [comment]
How can we reproduce it?  add some code for reproduce would be great.

**Comment by hhhyang** [comment]
@fifthangel do you have solved this problem? i also catch this exception!

**Comment by hhhyang** [comment]
> How can we reproduce it? add some code for reproduce would be great.

@liangyuanpeng 

i just use the example code snippet to producing this bug.

```java
try {
                Client client = Client.builder().endpoints("http://10.181.109.24:8379").build();

                KV kvClient = client.getKVClient();
                ByteSequence key = ByteSequence.from("test_key".getBytes());
                ByteSequence value = ByteSequence.from("test_value".getBytes());

                kvClient.put(key, value).get();
            } catch (InterruptedException | ExecutionException e) {

                log.info("{}", ExceptionUtils.getStackTrace(e));
            }
```

the output exception stack information:

```
2022-08-07 16:26:21.431 ERROR 22014 --- [ault-executor-0] io.grpc.internal.ManagedChannelImpl      : [Channel<1>: (ip:///10.181.109.24:8379)] Uncaught exception in the SynchronizationContext. Panic!

java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocator.<init>(ZIIIIIIZ)V
	at io.grpc.netty.Utils.createByteBufAllocator(Utils.java:176) ~[grpc-netty-1.41.0.jar:1.41.0]
	at io.grpc.netty.Utils.access$000(Utils.java:75) ~[grpc-netty-1.41.0.jar:1.41.0]
	at io.grpc.netty.Utils$ByteBufAllocatorPreferDirectHolder.<clinit>(Utils.java:97) ~[grpc-netty-1.41.0.jar:1.41.0]
	at io.grpc.netty.Utils.getByteBufAllocator(Utils.java:144) ~[grpc-netty-1.41.0.jar:1.41.0]
	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:233) ~[grpc-netty-1.41.0.jar:1.41.0]
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34) ~[grpc-core-1.41.0.jar:1.41.0]
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34) ~[grpc-core-1.41.0.jar:1.41.0]
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:259) ~[grpc-core-1.41.0.jar:1.41.0]
	at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:66) ~[grpc-core-1.41.0.jar:1.41.0]
	at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:201) ~[grpc-core-1.41.0.jar:1.41.0]
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95) [grpc-api-1.41.0.jar:1.41.0]
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127) [grpc-api-1.41.0.jar:1.41.0]
	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1872) [grpc-core-1.41.0.jar:1.41.0]
	at io.grpc.NameResolver$Listener2.onAddresses(NameResolver.java:210) [grpc-api-1.41.0.jar:1.41.0]
	at io.etcd.jetcd.resolver.IPNameResolver.doResolve(IPNameResolver.java:136) [jetcd-core-0.5.11.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]

2022-08-07 16:26:21.446  INFO 22014 --- [           main] com.example.etcd.EtcdApplication         : java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.example.etcd.EtcdApplication.lambda$runner$0(EtcdApplication.java:43)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.example.etcd.EtcdApplication.main(EtcdApplication.java:27)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at io.etcd.jetcd.ClientConnectionManager.lambda$null$3(ClientConnectionManager.java:287)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.etcd.jetcd.auth.AuthInterceptor$1$1.onClose(AuthInterceptor.java:101)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
Caused by: java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocator.<init>(ZIIIIIIZ)V
	at io.grpc.netty.Utils.createByteBufAllocator(Utils.java:176)
	at io.grpc.netty.Utils.access$000(Utils.java:75)
	at io.grpc.netty.Utils$ByteBufAllocatorPreferDirectHolder.<clinit>(Utils.java:97)
	at io.grpc.netty.Utils.getByteBufAllocator(Utils.java:144)
	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:233)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:259)
	at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:66)
	at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:201)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1872)
	at io.grpc.NameResolver$Listener2.onAddresses(NameResolver.java:210)
	at io.etcd.jetcd.resolver.IPNameResolver.doResolve(IPNameResolver.java:136)
	... 3 more
```
```
enviroment:
jetcd version: 0.5.7 or 0.5.11 or 0.7.3
java version: 1.8.0_191
etcd version: 3.5.0
spring-boot: 2.3.1.RELEASE
```

**Comment by hhhyang** [comment]
@fifthangel perhaps you can reference to #956 , this problem has been solved there

**Comment by lburgazzoli** [comment]
Duplicated of #956
