### ISSUE TITLE
Can the HttpResolverProvider enable clients to automatically perceive the changes of etcd cluster nodes? Can you write a Demo for me?

### ISSUE THREAD

**Issue by luomengY** [etcd-io/jetcd#1101]
Can the HttpResolverProvider enable clients to automatically perceive the changes of etcd cluster nodes? Can you write a Demo for me?

**Comment by lburgazzoli** [comment]
the HttpResolverProvider and the IpResolverProvider do not support dynamic reconfiguration of clients, the  DnsSrvNameResolver does.

It is not really clear what you are trying to achieve especially because you are opening tons of issues without a clear explanation

**Comment by luomengY** [comment]
Let's say I have an etcd cluster :etcd0,etcd1,etcd2; To create a client: Client client = Client.builder().endpoints(" http://etcd0:2379" , " http://etcd1:2379" , " http://etcd2:2379") .build(); Scenario 1: If I add etcd3 and etcd4 to the cluster now, can the endpoints of the established clients automatically perceive the newly added nodes etcd3 and etcd4?
 Scenario 2: Based on scenario 1, now remove etcd0,etcd1 and etcd2 from the cluster and only keep etcd3 and etcd4. Can the established client work? Can it sense that the nodes in the current cluster only have etcd3 and etcd4? These two scenarios are the ones I'm talking about where the established client can automatically sense changes in the cluster nodes.

**Comment by lburgazzoli** [comment]
thatbis clear, how do you expect the ned nodes to be discovered ? in other words how is providing the new list of nodes ?

**Comment by luomengY** [comment]
I only need the client that has been created to work normally under scenario 1 and scenario 2, because the endpoints of the client I created at the beginning are etcd0,etcd1 and etcd2. Finally, only etcd3 and etcd4 are left in my cluster. Can my client still work normally at this time? Can you connect to the changed cluster?

**Comment by luomengY** [comment]
Yes, as far as I know only dns+svr can do this, but I see that 0.7.3 no longer supports.uriresolverLoader. How can I link DnsSrvNameResolver to etcd client? Here's how you used to look at other people:
 final String[] etcdEndpoints = {" srv://_etcd-client._tcp.example.com" }; Client.builder().endpoints(etcdEndpoints) .uriResolverLoader(() -> { final Collection< URIResolver> resolvers = new ArrayList< > (a); resolvers.add(new DnsSrvUriResolver()); return resolvers; }) .loadBalancerFactory(Objects.requireNonNull(LoadBalancerRegistry.getDefaultRegistry() .getProvider(" round_robin") )) .build();

**Comment by lburgazzoli** [comment]
programmatically registering a resolver has been deprecated in grpc-java since some time so jetcd cannot relay on such mechanism anymore.

The way it work as today is based on the uri scheme so i.e. using 'ip' as scheme, would trigger the IpResolver to be used. 

If dns+srv is used as scheme, then the DnsSrvResolver is used.

**Comment by luomengY** [comment]
How do I create an etcd client if I want to use dns+srv as a scheme? How do I connect DnsSrvResolver to etd client here? Is it possible to just write it like this? 
final String[] etcdEndpoints = {" srv://_etcd-client._tcp.example.com" }; Client.builder().endpoints(etcdEndpoints) .build();

**Comment by luomengY** [comment]
Does dns+srv create clients like this? Client client=Client.builder().target(" dns+srv:///_etcd-client._tcp.example.com") .build();

**Comment by lburgazzoli** [comment]
yes, of course you need to update the srv record in order to the client to discover new nodes

**Comment by luomengY** [comment]
I tried it like above and got an error: Channel< 1> : (dns+srv:///_etcd-client._tcp.k8s.com)] Failed to resolve name

**Comment by luomengY** [comment]
My srv record looks like this :_etcd-client._tcp.k8s.com

**Comment by lburgazzoli** [comment]
can you try to debug the code ?

**Comment by luomengY** [comment]
The following error is reported:
警告: [Channel<1>: (dns+srv:///_etcd-client._tcp.hbm.com)] Failed to resolve name. status=Status{code=NOT_FOUND, description=null, cause=null}
11月 07, 2022 1:33:11 下午 io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext

**Comment by luomengY** [comment]
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.IllegalArgumentException: cannot find a NameResolver for dns+srv:///_etcd-client._tcp.hbm.com
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:771)
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:780)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:660)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
	at io.vertx.grpc.VertxChannelBuilder.build(VertxChannelBuilder.java:302)
	at io.etcd.jetcd.impl.ClientConnectionManager.getChannel(ClientConnectionManager.java:89)
	at io.etcd.jetcd.impl.ClientConnectionManager.newStub(ClientConnectionManager.java:121)
	at io.etcd.jetcd.impl.LockImpl.<init>(LockImpl.java:40)
	at io.etcd.jetcd.impl.ClientImpl.lambda$new$6(ClientImpl.java:54)
	at io.etcd.jetcd.support.MemorizingClientSupplier.get(MemorizingClientSupplier.java:37)
	at io.etcd.jetcd.impl.ClientImpl.getLockClient(ClientImpl.java:90)
	at JEtcdTestMaster.setUp(JEtcdTestMaster.java:38)
	at JEtcdTestMaster.lockTest1toMaster(JEtcdTestMaster.java:83)
	at JEtcdTestMaster.run(JEtcdTestMaster.java:121)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by luomengY** [comment]
[root@node15 disk1]# dig @10.40.128.14 +noall +answer SRV _etcd-client._tcp.hbm.com
_etcd-client._tcp.hbm.com. 0	IN	SRV	0 100 4379 etcd3.hbm.com.
_etcd-client._tcp.hbm.com. 0	IN	SRV	0 100 4379 etcd2.hbm.com.
_etcd-client._tcp.hbm.com. 0	IN	SRV	0 100 4379 etcd1.hbm.com.

**Comment by luomengY** [comment]
The debug code reports the above errors. Can you help me find out why?

**Comment by lburgazzoli** [comment]
you must debug the code using a debugger to find out the root cause

**Comment by luomengY** [comment]
WARNING: Default DNS servers: [/2001:4860:4860:0:0:0:0:8888:53, /2001:4860:4860:0:0:0:0:8844:53] (Google Public DNS as a fallback)
java.lang.IllegalArgumentException: cannot find a NameResolver for dns+srv:///_etcd-client._tcp.hbm.com
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:771)
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:780)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:660)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
	at io.vertx.grpc.VertxChannelBuilder.build(VertxChannelBuilder.java:302)
	at io.etcd.jetcd.impl.ClientConnectionManager.getChannel(ClientConnectionManager.java:89)
	at io.etcd.jetcd.impl.ClientConnectionManager.newStub(ClientConnectionManager.java:121)
	at io.etcd.jetcd.impl.LockImpl.<init>(LockImpl.java:40)
	at io.etcd.jetcd.impl.ClientImpl.lambda$new$6(ClientImpl.java:54)
	at io.etcd.jetcd.support.MemorizingClientSupplier.get(MemorizingClientSupplier.java:37)
	at io.etcd.jetcd.impl.ClientImpl.getLockClient(ClientImpl.java:90)
	at JEtcdTestMaster.setUp(JEtcdTestMaster.java:38)
