### ISSUE TITLE
How to pass the username and password in etcd java client 

### ISSUE THREAD

**Issue by irfanjs** [etcd-io/jetcd#1238]
**Version** : 
ETCDCTL_API=3 
ETCD bitnami chart for kubernetes : 3.5.9
jetcd java client version :  0.7.5

**what we have done** 
we have created simple springboot app to connect to etcd server . This etcd POD is deployed into one of the kubernetes cluster . 
we have taken sample example from jetcd github repo and trying to get the values of key . 

```
public class TestClient {

	public static void main(String[] args) throws InterruptedException, ExecutionException {
		// TODO Auto-generated method stub
		
		// create client using
		
		// create client using endpoints
		Client client = Client.builder().endpoints("http://34.238.182.142:32030").build();
		
		KV kvClient = client.getKVClient();
		ByteSequence key = ByteSequence.from("test_key".getBytes());
		ByteSequence value = ByteSequence.from("test_value".getBytes());
		
		kvClient.put(key, value).get();

	}

}
```
**what is the issue** 

we are getting below error : 
```
Exception in thread "main" java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: etcdserver: user name is empty
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at oe.etcd.etcd.TestClient.main(TestClient.java:25)
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: etcdserver: user name is empty
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:471)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.j

```

Not getting how to pass the username and password while building the client. any example please ? 
we tried searching docs and got some auth headers but not getting how to use that . 

Any references OR doc would be much appreciated. 
Please suggest

**Comment by lburgazzoli** [comment]
Something like:

```java
var client = Client.builder()
    .endpoints("http://34.238.182.142:32030")
    .user("foo")
    .password("bar")
    .build();
```

**Comment by irfanjs** [comment]
@lburgazzoli : I tried but not able to pass user/password . 
after setting the endpoint , the user and password methods are not accessible . 
Can you please give me working example ?

**Comment by liangyuanpeng** [comment]
> I tried but not able to pass user/password .

Could you please provide some test code for it?  
@irfanjs  
I have tested it and it's working for me.


```java
        String cluster0 = "http://127.0.0.1:2379";
        ClientBuilder clientBuilder = Client.builder()
                .user(ByteSequence.from("root".getBytes()))
                .password(ByteSequence.from("root".getBytes()))
                .endpoints(cluster0);
        Client client = clientBuilder.build();
        KV kvClient = client.getKVClient();
        ByteSequence data = ByteSequence.from("hello".getBytes());
        CompletableFuture<PutResponse> put = kvClient.put(data, data);
        PutResponse resp = put.join();
        log.info("resp:{}|{}",resp.getHeader().getRaftTerm(),resp.getPrevKv().getCreateRevision());
```

**Comment by irfanjs** [comment]
@liangyuanpeng : Thank you so much . It worked. 👍
