### ISSUE TITLE
io.etcd.jetcd.launcher.Etcd.builder().build() leaks Network.newNetwork()

### ISSUE THREAD

**Issue by faucct** [etcd-io/jetcd#1271]
**Versions**
- etcd: 0.4.1
- jetcd: 0.7.6
- java: 11

**Describe the bug**
When not specifying the network for the etcd cluster a new one gets created, which no-one destroys. When you are creating and destroying a lot of clusters at some point you run out of networks and get this error:

```
[2023-11-21T06:01:17.270Z]     ERROR [Nov 21 06:01:17.143] [_project=factor-service] [thread=Thread-9833] [logger=?.i.4.5]] Could not start container
[2023-11-21T06:01:17.270Z]     com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network"}
[2023-11-21T06:01:17.270Z] 
[2023-11-21T06:01:17.270Z]     	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241)
[2023-11-21T06:01:17.270Z]     	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:124)
[2023-11-21T06:01:17.270Z]     	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateNetworkCmdExec.execute(CreateNetworkCmdExec.java:27)
[2023-11-21T06:01:17.270Z]     	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateNetworkCmdExec.execute(CreateNetworkCmdExec.java:12)
[2023-11-21T06:01:17.270Z]     	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
[2023-11-21T06:01:17.270Z]     	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
[2023-11-21T06:01:17.270Z]     	at org.testcontainers.containers.Network$NetworkImpl.create(Network.java:93)
[2023-11-21T06:01:17.270Z]     	at org.testcontainers.containers.Network$NetworkImpl.getId(Network.java:62)
[2023-11-21T06:01:17.270Z]     	at org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:868)
[2023-11-21T06:01:17.270Z]     	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:378)
[2023-11-21T06:01:17.270Z]     	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
[2023-11-21T06:01:17.270Z]     	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
[2023-11-21T06:01:17.270Z]     	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
[2023-11-21T06:01:17.270Z]     	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
[2023-11-21T06:01:17.270Z]     	at io.etcd.jetcd.launcher.EtcdContainer.start(EtcdContainer.java:165)
[2023-11-21T06:01:17.270Z]     	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Expected behavior**
I expect the etcd cluster either destroy the network it has created, either use Network.SHARED by default.

**Comment by lburgazzoli** [comment]
can you worn on a fix ?

**Comment by lburgazzoli** [comment]
Fixed with https://github.com/etcd-io/jetcd/pull/1273
