### ISSUE TITLE
Developing jetcd with Eclipse and M2E is a PITA

### ISSUE THREAD

**Issue by vorburger** [etcd-io/jetcd#340]
I have just tried to import this project into Eclipse with M2E (Maven integration) to make a small contribution, and found it to be quite a PITA. Therefore opening this issue to group a number of things that need to be done to make this smoother.

**Comment by vorburger** [comment]
Also this 5th problem from the `protobuf-maven-plugin` and `depends-maven-plugin`, both of which declare that they can run in M2E (their default built-in Lifecycle Mapping, seen in Project > Properties > Maven > Lifecycle Mapping, is Mapping: execute from Source: Extension), but that is a sham - they don't really run well in Eclipse... e.g. they're incapable of performing workspace dependency resolution. Therefore it's simplest is to just make them be ignored, in Eclipse (only, of course). Everyone typically first once does a build on the CLI with `mvn` anyway - and then after that one wants his or her IDE to "just work" without this kind of non-sense:

```
Description	Resource	Path	Location	Type
Failed to execute goal on project jetcd-core: Could not resolve dependencies for project io.etcd:jetcd-core:bundle:0.3.0-SNAPSHOT: The following artifacts could not be resolved: io.etcd:jetcd-common:jar:0.3.0-SNAPSHOT, io.etcd:jetcd-resolver:jar:0.3.0-SNAPSHOT, org.mockito:mockito-core:jar:2.21.0, io.netty:netty-tcnative-boringssl-static:jar:${os.detected.classifier}:2.0.12.Final, org.testcontainers:testcontainers:jar:1.8.3: Cannot access opendaylight-snapshot (https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/) in offline mode and the artifact io.etcd:jetcd-common:jar:0.3.0-SNAPSHOT has not been downloaded from it before. (org.apache.servicemix.tooling:depends-maven-plugin:1.4.0:generate-depends-file:generate-depends-file:generate-resources)

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project jetcd-core: Could not resolve dependencies for project io.etcd:jetcd-core:bundle:0.3.0-SNAPSHOT: The following artifacts could not be resolved: io.etcd:jetcd-common:jar:0.3.0-SNAPSHOT, io.etcd:jetcd-resolver:jar:0.3.0-SNAPSHOT, org.mockito:mockito-core:jar:2.21.0, io.netty:netty-tcnative-boringssl-static:jar:${os.detected.classifier}:2.0.12.Final, org.testcontainers:testcontainers:jar:1.8.3: Cannot access opendaylight-snapshot (https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/) in offline mode and the artifact io.etcd:jetcd-common:jar:0.3.0-SNAPSHOT has not been downloaded from it before.
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:269)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:147)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:246)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:330)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project io.etcd:jetcd-core:bundle:0.3.0-SNAPSHOT: The following artifacts could not be resolved: io.etcd:jetcd-common:jar:0.3.0-SNAPSHOT, io.etcd:jetcd-resolver:jar:0.3.0-SNAPSHOT, org.mockito:mockito-core:jar:2.21.0, io.netty:netty-tcnative-boringssl-static:jar:${os.detected.classifier}:2.0.12.Final, org.testcontainers:testcontainers:jar:1.8.3: Cannot access opendaylight-snapshot (https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/) in offline mode and the artifact io.etcd:jetcd-common:jar:0.3.0-SNAPSHOT has not been downloaded from it before.
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:208)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:243)
	... 33 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: io.etcd:jetcd-common:jar:0.3.0-SNAPSHOT, io.etcd:jetcd-resolver:jar:0.3.0-SNAPSHOT, org.mockito:mockito-core:jar:2.21.0, io.netty:netty-tcnative-boringssl-static:jar:${os.detected.classifier}:2.0.12.Final, org.testcontainers:testcontainers:jar:1.8.3: Cannot access opendaylight-snapshot (https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/) in offline mode and the artifact io.etcd:jetcd-common:jar:0.3.0-SNAPSHOT has not been downloaded from it before.
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:355)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:202)
	... 34 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: io.etcd:jetcd-common:jar:0.3.0-SNAPSHOT, io.etcd:jetcd-resolver:jar:0.3.0-SNAPSHOT, org.mockito:mockito-core:jar:2.21.0, io.netty:netty-tcnative-boringssl-static:jar:${os.detected.classifier}:2.0.12.Final, org.testcontainers:testcontainers:jar:1.8.3: Cannot access opendaylight-snapshot (https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/) in offline mode and the artifact io.etcd:jetcd-common:jar:0.3.0-SNAPSHOT has not been downloaded from it before.
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:338)
	... 35 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Cannot access opendaylight-snapshot (https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/) in offline mode and the artifact io.etcd:jetcd-common:jar:0.3.0-SNAPSHOT has not been downloaded from it before.
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:369)
	... 37 more
Caused by: org.eclipse.aether.transfer.RepositoryOfflineException: Cannot access opendaylight-snapshot (https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/) in offline mode
	at org.eclipse.aether.internal.impl.DefaultOfflineController.checkOffline(DefaultOfflineController.java:84)
	at org.eclipse.aether.internal.impl.Utils.checkOffline(Utils.java:124)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:365)
	... 37 more
	pom.xml	/com.coreos.jetcd-core	line 23	Maven Build Problem
```

Therefore proposing https://github.com/etcd-io/jetcd/pull/355.

**Comment by vorburger** [comment]
Re. the 2nd problem (above) re. os-maven-plugin; I think I've found a very nice solution, see my new comment in https://github.com/trustin//issues/34 ... I'll try raising a PR which applies that trick to jetcd, as soon as my other pending PRs re. this are merged.
