### ISSUE TITLE
Build Failure java.lang.NoClassDefFoundError: io/etcd/jetcd/ByteSequence in OSGi Karaf IT

### ISSUE THREAD

**Issue by vorburger** [etcd-io/jetcd#434]
Hitting a local build failure, despite the last merged PR (#432) having been green:

```
git pull
git rev-parse --short HEAD
f6dbd64
mvn clean package

[org.ops4j.pax.exam.container.remote.RBCRemoteTarget] : Installed bundle (from stream) as ID: 54
[org.ops4j.pax.exam.junit.impl.ProbeRunner] : Invoke testServiceAvailability @ [TestAddress:PaxExam-7926fd3f-884c-44f8-b062-4a76cb4b3191 root:PaxExam-2c53a5ca-6f68-4ff4-bef1-0653d6b208ed] Arguments: [Ljava.lang.Object;@1e04fa0a
[org.ops4j.pax.exam.container.remote.RBCRemoteTarget] : call [[TestAddress:PaxExam-7926fd3f-884c-44f8-b062-4a76cb4b3191 root:PaxExam-2c53a5ca-6f68-4ff4-bef1-0653d6b208ed]]
java.lang.NoClassDefFoundError: io/etcd/jetcd/ByteSequence
	at io.etcd.jetcd.osgi.ClientServiceChecks.testServiceAvailability(ClientServiceChecks.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runLeafWithRetry(ContainerTestRunner.java:97)
	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChildWithRetry(ContainerTestRunner.java:84)
	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:75)
	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:43)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.invokeViaJUnit(JUnitProbeInvoker.java:124)
	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.findAndInvoke(JUnitProbeInvoker.java:97)
	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.call(JUnitProbeInvoker.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ops4j.pax.exam.rbc.internal.RemoteBundleContextImpl.remoteCall(RemoteBundleContextImpl.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.etcd.jetcd.ByteSequence not found by io.etcd.jetcd-all [12]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1639)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1414)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1660)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1590)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 46 more
[org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer] : Shutting down the test container (Pax Runner)
[org.ops4j.pax.exam.spi.reactors.ReactorManager] : suite finished
[com.github.dockerjava.core.command.AbstrDockerCmd] : Cmd: 88d220faf854703b880641ce06f902569c8f65cc2763b3275ef75342919cf215,false,com.github.dockerjava.core.exec.InspectContainerCmdExec@73194df
[com.github.dockerjava.core.exec.InspectContainerCmdExec] : GET: OkHttpWebTarget(okHttpClient=org.testcontainers.shaded.okhttp3.OkHttpClient@5af3afd9, baseUrl=http://docker.socket/, path=[/containers/88d220faf854703b880641ce06f902569c8f65cc2763b3275ef75342919cf215/json], queryParams={})
[com.github.dockerjava.core.command.AbstrDockerCmd] : Cmd: 88d220faf854703b880641ce06f902569c8f65cc2763b3275ef75342919cf215,<null>,com.github.dockerjava.core.exec.KillContainerCmdExec@40db2a24
[com.github.dockerjava.core.command.AbstrDockerCmd] : Cmd: 88d220faf854703b880641ce06f902569c8f65cc2763b3275ef75342919cf215,false,com.github.dockerjava.core.exec.InspectContainerCmdExec@10cf09e8
[com.github.dockerjava.core.exec.InspectContainerCmdExec] : GET: OkHttpWebTarget(okHttpClient=org.testcontainers.shaded.okhttp3.OkHttpClient@5af3afd9, baseUrl=http://docker.socket/, path=[/containers/88d220faf854703b880641ce06f902569c8f65cc2763b3275ef75342919cf215/json], queryParams={})
[com.github.dockerjava.core.command.AbstrDockerCmd] : Cmd: 88d220faf854703b880641ce06f902569c8f65cc2763b3275ef75342919cf215,true,true,com.github.dockerjava.core.exec.RemoveContainerCmdExec@68b32e3e
[org.testcontainers.utility.ResourceReaper] : Removed container and associated volume(s): gcr.io/etcd-development/etcd:v3.3
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.027 s <<< FAILURE! - in io.etcd.jetcd.osgi.PaxExamWrapperTest
[ERROR] testClientServiceChecks(io.etcd.jetcd.osgi.PaxExamWrapperTest)  Time elapsed: 12.658 s  <<< ERROR!
java.lang.ClassNotFoundException: io.etcd.jetcd.ByteSequence not found by io.etcd.jetcd-all [12]

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   PaxExamWrapperTest.testClientServiceChecks » ClassNotFound io.etcd.jetcd.ByteS...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] jetcd 0.3.0-SNAPSHOT ............................... SUCCESS [  0.189 s]
[INFO] jetcd-launcher ..................................... SUCCESS [  7.989 s]
[INFO] jetcd-launcher-maven-plugin ........................ SUCCESS [  6.500 s]
[INFO] jetcd-common ....................................... SUCCESS [  2.839 s]
[INFO] jetcd-resolver ..................................... SUCCESS [  3.088 s]
[INFO] jetcd-core ......................................... SUCCESS [01:54 min]
[INFO] jetcd-launcher-maven-plugin-test ................... SUCCESS [  6.143 s]
[INFO] jetcd-resolver-dns-srv ............................. SUCCESS [  5.870 s]
[INFO] jetcd-all .......................................... SUCCESS [  7.220 s]
[INFO] jetcd-osgi-parent .................................. SUCCESS [  0.003 s]
[INFO] jetcd-osgi ......................................... SUCCESS [  0.391 s]
[INFO] jetcd-karaf ........................................ FAILURE [ 46.267 s]
[INFO] jetcd-watch-example 0.1.0-SNAPSHOT ................. SKIPPED
[INFO] jetcd-simple-ctl 0.1.0-SNAPSHOT .................... SKIPPED
[INFO] jetcd-examples 0.1.0-SNAPSHOT ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:24 min
[INFO] Finished at: 2018-11-06T10:07:50+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project jetcd-karaf: There are test failures.
```

**Comment by vorburger** [comment]
> mvn clean package

Oh ... it's OK with `mvn clean install` - I should know better!  (It's cauz Pax Exam doesn't respect the Reactor, but reads local repo.)
