### ISSUE TITLE
Please refer  the individual test results.

### ISSUE THREAD

**Issue by Liberxue** [etcd-io/jetcd#449]
```
[INFO] Reactor Summary:
[INFO] 
[INFO] jetcd 0.3.0-SNAPSHOT ............................... SUCCESS [  0.441 s]
[INFO] jetcd-launcher ..................................... SUCCESS [  3.119 s]
[INFO] jetcd-launcher-maven-plugin ........................ SUCCESS [  3.773 s]
[INFO] jetcd-common ....................................... SUCCESS [  1.867 s]
[INFO] jetcd-resolver ..................................... SUCCESS [  2.202 s]
[INFO] jetcd-core ......................................... FAILURE [ 30.624 s]
[INFO] jetcd-launcher-maven-plugin-test ................... SKIPPED
[INFO] jetcd-resolver-dns-srv ............................. SKIPPED
[INFO] jetcd-all .......................................... SKIPPED
[INFO] jetcd-osgi-parent .................................. SKIPPED
[INFO] jetcd-osgi ......................................... SKIPPED
[INFO] jetcd-karaf ........................................ SKIPPED
[INFO] jetcd-watch-example 0.1.0-SNAPSHOT ................. SKIPPED
[INFO] jetcd-simple-ctl 0.1.0-SNAPSHOT .................... SKIPPED
[INFO] jetcd-examples 0.1.0-SNAPSHOT ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42.919 s
[INFO] Finished at: 2018-11-22T19:45:02+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project jetcd-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/liberxue/java/jetcd/jetcd-core/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] 
[ERROR] An error occurred while instantiating class io.etcd.jetcd.ClusterClientTest: null
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] 
[ERROR] An error occurred while instantiating class io.etcd.jetcd.ClusterClientTest: null
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:656)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jetcd-core

```

```
~/java/jetcd(master) » mvn -v                                                                                                                                                                       liberxue@liberxuedeMacBook-Pro
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T02:33:14+08:00)
Maven home: /Users/liberxue/java/maven/apache-maven-3.5.4
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre
Default locale: en_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.14", arch: "x86_64", family: "mac"
------------------------------------------------------------
mvn clean package -Dmaven.test.skip=true

[ERROR] Failed to execute goal io.etcd:jetcd-launcher-maven-plugin:0.3.0-SNAPSHOT:start (start-etcd) on project jetcd-launcher-maven-plugin-test: Execution start-etcd of goal io.etcd:jetcd-launcher-maven-plugin:0.3.0-SNAPSHOT:start failed: Could not find a valid Docker environment. Please see logs and check configuration -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jetcd-launcher-maven-plugin-test

```

**Comment by lburgazzoli** [comment]
do you have docker installed ?

**Comment by Liberxue** [comment]
Uh huh 😅
Why do you want to start docker to faint? . .

**Comment by lburgazzoli** [comment]
it is used to spin up etcd server instances for testing purpose

**Comment by Liberxue** [comment]
Ok, ☆⌒(*＾-゜)v THX , learning new posture, this exception handling is also weird 😅
