### ISSUE TITLE
can not connet etcd server with username/password authentication when auth disable

### ISSUE THREAD

**Issue by amanda2015** [etcd-io/jetcd#468]
When I execute command "ETCDCTL_API=3 etcdctl auth disable" in the etcd server. And in my java API I create a connection with username/password authentication.  When I get ot set a key. That will throw an exception "com.coreos.jetcd.common.exception.EtcdException: etcdserver: authentication is not enabled".
But I can get or set a key in my etcd server with username/password authentication. Why throw exceptions in Java API? Thanks
The jetcd version I imported is version 0.0.2.

**Comment by lburgazzoli** [comment]
The error comes from the server, do you mind checking what the server logs say ?

**Comment by amanda2015** [comment]
Thank you for your response. I think I can get a key-value in Java API just like I can get a key-value with 
 etcdctl command when I create a connection with username/password authentication and auth disable.
The logs are as follows(e.g. I get a key):
Exception in thread "main" com.coreos.jetcd.common.exception.EtcdException: etcdserver: authentication is not enabled
    at com.coreos.jetcd.common.exception.EtcdExceptionFactory.newEtcdException(EtcdExceptionFactory.java:34)
    at com.coreos.jetcd.common.exception.EtcdExceptionFactory.fromStatus(EtcdExceptionFactory.java:82)
    at com.coreos.jetcd.common.exception.EtcdExceptionFactory.toEtcdException(EtcdExceptionFactory.java:78)
    at com.coreos.jetcd.common.exception.EtcdExceptionFactory.toEtcdException(EtcdExceptionFactory.java:73)
    at com.coreos.jetcd.internal.impl.ClientConnectionManager.generateToken(ClientConnectionManager.java:249)
    at com.coreos.jetcd.internal.impl.ClientConnectionManager.getToken(ClientConnectionManager.java:113)
    at com.coreos.jetcd.internal.impl.ClientConnectionManager.access$100(ClientConnectionManager.java:57)
    at com.coreos.jetcd.internal.impl.ClientConnectionManager$AuthTokenInterceptor$1.start(ClientConnectionManager.java:268)
    at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:293)
    at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:268)
    at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:177)
    at com.coreos.jetcd.api.KVGrpc$KVFutureStub.range(KVGrpc.java:504)
    at com.coreos.jetcd.internal.impl.KVImpl.lambda$get$2(KVImpl.java:110)
    at com.coreos.jetcd.internal.impl.Util.toCompletableFutureWithRetry(Util.java:104)
    at com.coreos.jetcd.internal.impl.KVImpl.get(KVImpl.java:109)
    at com.coreos.jetcd.internal.impl.KVImpl.get(KVImpl.java:86)
    at com.nokia.csdc.KVResponse.GetResponse(KVResponse.java:50)

**Comment by lburgazzoli** [comment]
The error comes from the server and I suspect etcdctl simply ignores it however, I'm not very sure we should do the same.

**Comment by amanda2015** [comment]
OK. I got it. Thanks very much.
