### ISSUE TITLE
etcdserver: mvcc: required revision is a future revision

### ISSUE THREAD

**Issue by devenfan** [etcd-io/jetcd#480]
We've meet this issue when we try to watch a key like /a/b/c, can somebody give us a clue?

ETCD version: 
{"etcdserver":"3.3.8","etcdcluster":"3.3.0"}

<pre>
2019-01-07 21:31:03.077 ERROR [][][][][]etcdserver: mvcc: required revision is a future revision
com.example.etcd.watcher.AsyncWatcher
com.coreos.jetcd.common.exception.EtcdException: etcdserver: mvcc: required revision is a future revision
        at com.coreos.jetcd.common.exception.EtcdExceptionFactory.newEtcdException(EtcdExceptionFactory.java:30)
        at com.coreos.jetcd.internal.impl.WatchImpl.processCanceled(WatchImpl.java:348)
        at com.coreos.jetcd.internal.impl.WatchImpl.processWatchResponse(WatchImpl.java:200)
        at com.coreos.jetcd.internal.impl.WatchImpl.access$100(WatchImpl.java:61)
        at com.coreos.jetcd.internal.impl.WatchImpl$1.onNext(WatchImpl.java:177)
        at com.coreos.jetcd.internal.impl.WatchImpl$1.onNext(WatchImpl.java:174)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:406)
        at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:36)
        at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:36)
        at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:36)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:530)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

</pre>

**Comment by lburgazzoli** [comment]
can you give more details ?
