### ISSUE TITLE
Fail to run "mvn test" in MacOS

### ISSUE THREAD

**Issue by MalcolmSanders** [etcd-io/jetcd#489]
Hi, all:

While I ran "mvn test" on macOS, such exception occurred:

-------------------------------------------------------------------------------------

09:58:03.000|INFO |org.testcontainers.DockerClientFactory - Connected to docker:
  Server Version: 18.03.0-ce
  API Version: 1.37
  Operating System: Docker for Mac
  Total Memory: 1998 MB
09:58:04.135|INFO |org.testcontainers.DockerClientFactory - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
09:59:24.361|ERROR|🐳 [gcr.io/etcd-development/etcd:v3.3] - Could not start container
java.lang.reflect.UndeclaredThrowableException: null
        at com.sun.proxy.$Proxy39.exec(Unknown Source) ~[?:?]
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:243) ~[testcontainers-1.10.5.jar:?]
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:216) ~[testcontainers-1.10.5.jar:?]
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76) ~[duct-tape-1.0.7.jar:?]
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:214) ~[testcontainers-1.10.5.jar:?]
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:203) ~[testcontainers-1.10.5.jar:?]
        at io.etcd.jetcd.launcher.EtcdContainer.start(EtcdContainer.java:145) ~[classes/:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.testcontainers.dockerclient.AuditLoggingDockerClient.lambda$wrappedCommand$14(AuditLoggingDockerClient.java:98) ~[testcontainers-1.10.5.jar:?]
        ... 8 more
Caused by: com.github.dockerjava.api.exception.DockerException: Mounts denied:
The path /var/folders/l0/6jlf9plj197g06f2mjkv1h480000gn/T/jetcd_test_etcd0_1713473062908495631/
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.

-------------------------------------------------------------------------------------

After investigation, I found it has sth to do with docker in macOS. The following question in stackoverflow shows exactly the same issue.
https://stackoverflow.com/questions/45122459/docker-mounts-denied-the-paths-are-not-shared-from-os-x-and-are-not-known

Since docker forbids to add /var/folder to its file sharing directories because /var/folder is actually a subdir of /private in macOS. My current solution is to reset environment variable "java.io.tmpdir" as follows:
`export _JAVA_OPTIONS=-Djava.io.tmpdir=/tmp/`

Is it the recommended solution to deal with such failure in macOS? Or maybe I should do some settings?

PS: It seems that testcontainer has adapted to macOS while create temporary directories. (Ref: org.testcontainers.utility#createTempDirectory())

**Comment by vorburger** [comment]
@MalcolmSanders if you want to help this project (jetcd), perhaps you could raise this Mac specific issue with the Testcontainers project itself (over on https://github.com/testcontainers/testcontainers-java/issues)? If there is anything which we can do better to make it easier for Mac users, we welcome a Pull Request from you.

**Comment by MalcolmSanders** [comment]
> @MalcolmSanders if you want to help this project (jetcd), perhaps you could raise this Mac specific issue with the Testcontainers project itself (over on https://github.com/testcontainers/testcontainers-java/issues)? If there is anything which we can do better to make it easier for Mac users, we welcome a Pull Request from you.

Thanks for replying. Previously I got a simple workaround, and I'm going to give a PR later.

**Comment by yb172** [comment]
Interestingly enough I see this error only for one test case: [WatchResumeTest](https://github.com/etcd-io/jetcd/blob/12ad75339701ed21816b99878088c9f13ec3b74a/jetcd-core/src/test/java/io/etcd/jetcd/WatchResumeTest.java#L41) and no error happens for other tests which use `EtcdClusterResource` (e.g. [WatchTest](https://github.com/etcd-io/jetcd/blob/12ad75339701ed21816b99878088c9f13ec3b74a/jetcd-core/src/test/java/io/etcd/jetcd/WatchTest.java#L52)).

`WatchResumeTest` is the only test which uses constructor with 4 parameters: name, nodes, ssl, restartable. `WatchTest` also fails if all four params are provided. However if 3 params are provided it works fine. So something is odd with `restartable` param.

**Comment by yb172** [comment]
Looks like while default `var/folders/...` causes trouble [other tmp dir `/private/var/tmp`](https://apple.stackexchange.com/a/131080) work fine.
