### ISSUE TITLE
Karaf fails to download

### ISSUE THREAD

**Issue by TisonKun** [etcd-io/jetcd#616]
```
[shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager] : Connection manager shut down Ignored FQCN: shaded.org.apache.commons.logging.impl.SLF4JLocationAwareLog
org.apache.karaf.features.internal.util.MultiException: Error:
	Error downloading mvn:io.etcd/jetcd-all/0.3.1-SNAPSHOT
	Error downloading mvn:io.etcd/jetcd-osgi/0.3.1-SNAPSHOT
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:457)
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:452)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:224)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.io.IOException: Error downloading mvn:io.etcd/jetcd-all/0.3.1-SNAPSHOT
		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
		... 3 more
	Caused by: java.io.IOException: Error resolving artifact io.etcd:jetcd-all:jar:0.3.1-SNAPSHOT: [Could not find artifact io.etcd:jetcd-all:jar:0.3.1-SNAPSHOT in apache (http://repository.apache.org/content/groups/snapshots-group/), Could not find artifact io.etcd:jetcd-all:jar:0.3.1-SNAPSHOT in ops4j.sonatype.snapshots.deploy (https://oss.sonatype.org/content/repositories/ops4j-snapshots/)]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
		at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:52)
		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
		... 7 more
		Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.etcd:jetcd-all:jar:0.3.1-SNAPSHOT in apache (http://repository.apache.org/content/groups/snapshots-group/)
			at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368)
			at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:642)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:489)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:390)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
			at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
			at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
			... 12 more
		Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.etcd:jetcd-all:jar:0.3.1-SNAPSHOT in ops4j.sonatype.snapshots.deploy (https://oss.sonatype.org/content/repositories/ops4j-snapshots/)
			at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368)
			at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:642)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:489)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:390)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
			at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
			at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
			... 12 more
	Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact io.etcd:jetcd-all:jar:0.3.1-SNAPSHOT
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:413)
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
		at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
		... 12 more
	Suppressed: java.io.IOException: Error downloading mvn:io.etcd/jetcd-osgi/0.3.1-SNAPSHOT
		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
		... 3 more
	Caused by: java.io.IOException: Error resolving artifact io.etcd:jetcd-osgi:jar:0.3.1-SNAPSHOT: [Could not find artifact io.etcd:jetcd-osgi:jar:0.3.1-SNAPSHOT in apache (http://repository.apache.org/content/groups/snapshots-group/), Could not find artifact io.etcd:jetcd-osgi:jar:0.3.1-SNAPSHOT in ops4j.sonatype.snapshots.deploy (https://oss.sonatype.org/content/repositories/ops4j-snapshots/)]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
		at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:52)
		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
		... 7 more
		Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.etcd:jetcd-osgi:jar:0.3.1-SNAPSHOT in apache (http://repository.apache.org/content/groups/snapshots-group/)
			at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368)
			at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:642)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:489)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:390)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
			at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
			at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
			... 12 more
		Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.etcd:jetcd-osgi:jar:0.3.1-SNAPSHOT in ops4j.sonatype.snapshots.deploy (https://oss.sonatype.org/content/repositories/ops4j-snapshots/)
			at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368)
			at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:642)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:489)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:390)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
			at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
			at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
			... 12 more
	Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact io.etcd:jetcd-osgi:jar:0.3.1-SNAPSHOT
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:413)
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
		at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
		... 12 more
[org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer] : Shutting down the test container (Pax Runner)
[com.github.dockerjava.core.command.AbstrDockerCmd] : Cmd: cab4f0e41597563daae926c8e05eded025dc42632f4607ee8ce48cf4ae234462,false,com.github.dockerjava.core.exec.InspectContainerCmdExec@4c4748bf
[com.github.dockerjava.core.exec.InspectContainerCmdExec] : GET: OkHttpWebTarget(okHttpClient=org.testcontainers.shaded.okhttp3.OkHttpClient@1de5f259, baseUrl=http://docker.socket/, path=[/containers/cab4f0e41597563daae926c8e05eded025dc42632f4607ee8ce48cf4ae234462/json], queryParams={})
[com.github.dockerjava.core.command.AbstrDockerCmd] : Cmd: cab4f0e41597563daae926c8e05eded025dc42632f4607ee8ce48cf4ae234462,<null>,com.github.dockerjava.core.exec.KillContainerCmdExec@47c4ecdc
[com.github.dockerjava.core.command.AbstrDockerCmd] : Cmd: cab4f0e41597563daae926c8e05eded025dc42632f4607ee8ce48cf4ae234462,false,com.github.dockerjava.core.exec.InspectContainerCmdExec@42f33b5d
[com.github.dockerjava.core.exec.InspectContainerCmdExec] : GET: OkHttpWebTarget(okHttpClient=org.testcontainers.shaded.okhttp3.OkHttpClient@1de5f259, baseUrl=http://docker.socket/, path=[/containers/cab4f0e41597563daae926c8e05eded025dc42632f4607ee8ce48cf4ae234462/json], queryParams={})
[com.github.dockerjava.core.command.AbstrDockerCmd] : Cmd: cab4f0e41597563daae926c8e05eded025dc42632f4607ee8ce48cf4ae234462,true,true,com.github.dockerjava.core.exec.RemoveContainerCmdExec@3d3ba765
[org.testcontainers.utility.ResourceReaper] : Removed container and associated volume(s): gcr.io/etcd-development/etcd:v3.3
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 185.194 s <<< FAILURE! - in io.etcd.jetcd.osgi.PaxExamWrapperTest
[ERROR] testClientServiceChecks  Time elapsed: 183.246 s  <<< ERROR!
java.lang.RuntimeException: Cannot get the remote bundle context
	at io.etcd.jetcd.osgi.PaxExamWrapperTest.testClientServiceChecks(PaxExamWrapperTest.java:53)
Caused by: java.rmi.NotBoundException: 28b90cc8-4358-4805-af33-3ac019fa93f6
	at io.etcd.jetcd.osgi.PaxExamWrapperTest.testClientServiceChecks(PaxExamWrapperTest.java:53)
```

**Comment by TisonKun** [comment]
If only I can config download from `https://repo1.maven.org/maven2/`...

**Comment by TisonKun** [comment]
I can see it is not about network issue, because when I manually did the change below tests passed

```
diff --git a/jetcd-osgi/jetcd-karaf/src/main/resources/features.xml b/jetcd-osgi/jetcd-karaf/src/main/resources/features.xml
index 981db06..e0f908c 100644
--- a/jetcd-osgi/jetcd-karaf/src/main/resources/features.xml
+++ b/jetcd-osgi/jetcd-karaf/src/main/resources/features.xml
@@ -82,8 +82,8 @@
         -->
 
         <!-- use jetcd-all until grpc fixes split package -->
-        <bundle>mvn:io.etcd/jetcd-all/${project.version}</bundle>
-        <bundle>mvn:io.etcd/jetcd-osgi/${project.version}</bundle>
+        <bundle>mvn:io.etcd/jetcd-all/0.3.0</bundle>
+        <bundle>mvn:io.etcd/jetcd-osgi/0.3.0</bundle>
 
     </feature>
 </features>
```

so the problem is that we do not publish jetcd-all:0.3.1-SNAPSHOT on any of

```
http://repo1.maven.org/maven2/
http://repository.apache.org/content/groups/snapshots-group/
https://oss.sonatype.org/content/repositories/snapshots/
https://oss.sonatype.org/content/repositories/ops4j-snapshots/
```

**Comment by lburgazzoli** [comment]
I see jetcd-all and jetcd-osgi in the snapshot repo:

- https://oss.sonatype.org/content/repositories/snapshots/io/etcd/jetcd-all/0.3.1-SNAPSHOT/
- https://oss.sonatype.org/content/repositories/snapshots/io/etcd/jetcd-osgi/0.3.1-SNAPSHOT/

**Comment by TisonKun** [comment]
@lburgazzoli thanks for your attention.

After a closer look at the log it seems only

http://repository.apache.org/content/groups/snapshots-group/
https://oss.sonatype.org/content/repositories/ops4j-snapshots/

have been scanned. Any ideas?

**Comment by TisonKun** [comment]
well, some of attempts may be suppressed...

however it is still strange to me that if I turn the version to 0.3.0 it can be properly resolved and to 0.3.1-SNAPSHOT it fails to be resolved.

**Comment by lburgazzoli** [comment]
it is likely the repository for oss snapshots has not been configured but if you are running the test from the repository, then you should have it locally. 

Maybe do a mvn install on the project root

**Comment by TisonKun** [comment]
>if you are running the test from the repository, then you should have it locally.
>
>Maybe do a mvn install on the project root

Yes you get it. Fixed by

```
$ (jetcd) mvn clean install -DskipTests
$ (jetcd) mvn test # successful
```

thanks!

**Comment by lburgazzoli** [comment]
You may just run `mvn clean install`, it should properly handle module intra-dependencies

**Comment by TisonKun** [comment]
@lburgazzoli sounds reasonable. The reported build order is

```
[INFO] Reactor Build Order:
[INFO] 
[INFO] jetcd                                                              [pom]
[INFO] jetcd-launcher                                                     [jar]
[INFO] jetcd-launcher-maven-plugin                               [maven-plugin]
[INFO] jetcd-common                                                    [bundle]
[INFO] jetcd-resolver                                                  [bundle]
[INFO] jetcd-core                                                      [bundle]
[INFO] jetcd-launcher-maven-plugin-test                                   [jar]
[INFO] jetcd-resolver-dns-srv                                          [bundle]
[INFO] jetcd-extensions                                                [bundle]
[INFO] jetcd-all                                                       [bundle]
[INFO] jetcd-osgi-parent                                                  [pom]
[INFO] jetcd-osgi                                                      [bundle]
[INFO] jetcd-karaf                                                     [bundle]
[INFO] jetcd-examples                                                     [pom]
[INFO] jetcd-watch                                                        [jar]
[INFO] jetcd-ctl                                                          [jar]
```

however, inside `jetcd-karaf` I found dependencies include only 

```xml
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>jetcd-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>jetcd-resolver</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>jetcd-launcher</artifactId>
            <scope>test</scope>
        </dependency>
```

without `jetcd-all`. Is it an error prone pom?
