### ISSUE TITLE
Watch: "Stream is already completed, no further calls are allowed"

### ISSUE THREAD

**Issue by aphyr** [etcd-io/jetcd#674]
With jetcd 0.4.1 and etcd 3.4.3, it looks like occasionally calls to create a watch can throw an IllegalStateException, complaining that the "Stream is already completed, no further calls are allowed".

```
java.lang.IllegalStateException: Stream is already completed, no further calls are allowed
        at com.google.common.base.Preconditions.checkState(Preconditions.java:510) ~[guava-26.0-android.jar:na]
        at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onNext(ClientCalls.java:340) ~[grpc-stub-1.24.0.jar:1.24.0]
        at io.etcd.jetcd.WatchImpl$WatcherImpl.resume(WatchImpl.java:154) ~[jetcd-core-0.4.1.jar:na]
        at io.etcd.jetcd.WatchImpl.watch(WatchImpl.java:81) ~[jetcd-core-0.4.1.jar:na]
        at io.etcd.jetcd.Watch.watch(Watch.java:108) ~[jetcd-core-0.4.1.jar:na]
        at jepsen.etcd.client$watch.invokeStatic(client.clj:594) ~[na:na]
        at jepsen.etcd.client$watch.invoke(client.clj:581) ~[na:na]
        at jepsen.etcd.watch$watch.invokeStatic(watch.clj:29) ~[na:na]
        at jepsen.etcd.watch$watch.invoke(watch.clj:17) ~[na:na]
        at jepsen.etcd.watch$watch_for.invokeStatic(watch.clj:88) ~[na:na]
        at jepsen.etcd.watch$watch_for.invoke(watch.clj:85) ~[na:na]
        at jepsen.etcd.watch.Client.invoke_BANG_(watch.clj:114) ~[na:na]
        at jepsen.core$invoke_op_BANG_$fn__5792.invoke(core.clj:220) ~[classes/:na]
        at jepsen.core$invoke_op_BANG_.invokeStatic(core.clj:220) [classes/:na]
        at jepsen.core$invoke_op_BANG_.invoke(core.clj:215) [classes/:na]
        at jepsen.core.ClientWorker.run_worker_BANG_(core.clj:352) [classes/:na]
        at jepsen.core$run_workers_BANG_$run__5783.invoke(core.clj:203) [classes/:na]
        at dom_top.core$real_pmap_helper$build_thread__214$fn__215.invoke(core.clj:146) [classes/:na]
        at clojure.lang.AFn.applyToHelper(AFn.java:152) [clojure-1.10.0.jar:na]
        at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.10.0.jar:na]
        at clojure.core$apply.invokeStatic(core.clj:665) [clojure-1.10.0.jar:na]
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973) [clojure-1.10.0.jar:na]
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973) [clojure-1.10.0.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:425) [clojure-1.10.0.jar:na]
        at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.10.0.jar:na]
        at clojure.lang.RestFn.applyTo(RestFn.java:132) [clojure-1.10.0.jar:na]
        at clojure.core$apply.invokeStatic(core.clj:669) [clojure-1.10.0.jar:na]
        at clojure.core$bound_fn_STAR_$fn__5734.doInvoke(core.clj:2003) [clojure-1.10.0.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:397) [clojure-1.10.0.jar:na]
        at clojure.lang.AFn.run(AFn.java:22) [clojure-1.10.0.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

This happened during a Jepsen test where we added and removed nodes to the cluster dynamically, so it might have something to do with membership changes. There were no other faults--partitions, process pauses, kills, etc. involved. Doesn't seem super common, but this does feel like something that might be a race condition, or if it's an IO thing, perhaps a more informative error message?

**Comment by lburgazzoli** [comment]
would it be possible to incorporate in some way your tests here ?

**Comment by aphyr** [comment]
They're available here: https://github.com/jepsen-io/etcd! I haven't written up documentation yet, but if you have a Jepsen environment available (see https://github.com/jepsen-io/jepsen#setting-up-a-jepsen-environment), you can run something like `lein run test -w watch --concurrency 2n --time-limit 600 --test-count 20`, with SHA 465aead72a3eaf3bb1978e39f5123897afcb96b1 and it should hopefully pop up in the logs.
