### ISSUE TITLE
Exception while getting value  java.lang.IllegalAccessError: tried to access field com.google.protobuf.AbstractMessage.memoizedSize from class

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [etcd-io/jetcd#688]
Using jETCd version: 0.4.1
etcd: 3.4.3

Exception in thread "grpc-default-executor-0" java.lang.IllegalAccessError: tried to access field com.google.protobuf.AbstractMessage.memoizedSize from class io.etcd.jetcd.api.RangeRequest
	at io.etcd.jetcd.api.RangeRequest.getSerializedSize(RangeRequest.java:674)
	at io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108)
	at io.grpc.internal.MessageFramer.getKnownLength(MessageFramer.java:205)
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:137)
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:53)
	at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)
	at io.grpc.internal.DelayedStream$6.run(DelayedStream.java:257)
	at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:163)
	at io.grpc.internal.DelayedStream.setStream(DelayedStream.java:132)
	at io.grpc.internal.DelayedClientTransport$PendingStream.createRealStream(DelayedClientTransport.java:358)
	at io.grpc.internal.DelayedClientTransport$PendingStream.access$300(DelayedClientTransport.java:341)
	at io.grpc.internal.DelayedClientTransport$5.run(DelayedClientTransport.java:300)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lburgazzoli** [comment]
Can you create a reproducer ?

**Comment by aphyr** [comment]
I'm seeing something very much like this in jetcd 0.6.1, in the [Jepsen etcd tests](https://github.com/jepsen-io/etcd):

```
Uncaught exception in thread grpc-default-executor-0:
                                 java.lang.Thread.run                  Thread.java:  833
   java.util.concurrent.ThreadPoolExecutor$Worker.run      ThreadPoolExecutor.java:  635
    java.util.concurrent.ThreadPoolExecutor.runWorker      ThreadPoolExecutor.java: 1136
                 io.grpc.internal.DelayedStream$4.run           DelayedStream.java:  148
            io.grpc.internal.DelayedStream.access$100           DelayedStream.java:   44
     io.grpc.internal.DelayedStream.drainPendingCalls           DelayedStream.java:  182
                 io.grpc.internal.DelayedStream$6.run           DelayedStream.java:  283
 io.grpc.internal.ForwardingClientStream.writeMessage  ForwardingClientStream.java:   37
         io.grpc.internal.AbstractStream.writeMessage          AbstractStream.java:   65
          io.grpc.internal.MessageFramer.writePayload           MessageFramer.java:  137
        io.grpc.internal.MessageFramer.getKnownLength           MessageFramer.java:  205
     io.grpc.protobuf.lite.ProtoInputStream.available        ProtoInputStream.java:  108
io.etcd.jetcd.api.MemberListRequest.getSerializedSize       MemberListRequest.java:  102
java.lang.IllegalAccessError: class io.etcd.jetcd.api.MemberListRequest tried to access private field com.google.protobuf.AbstractMessage.memoizedSize (io.etcd.jetcd.api.MemberListRequest and com.google.protobuf.AbstractMessage are in unnamed module of loader 'app')
```

Some googling suggests this could be due to incompatible versions of protobuf dependencies being on the classpath, but the only conflicting dependency I can find comes from jetcd itself, which requires both com.google.errorprone/error_prone_annotations 2.7.1 (via guava) and 2.9.0 (everything else). I've pinned it to both 2.7.1 and 2.9.0 and both give the same error.

**Comment by crimeminister** [comment]
I just encountered the same error while doing Java interop with Clojure:
```
Execution error (IllegalAccessError) at io.etcd.jetcd.api.PutRequest/getSerializedSize (PutRequest.java:175
class io.etcd.jetcd.api.PutRequest tried to access private field com.google.protobuf.AbstractMessage.memoizedSize
```
I am using jetcd `v0.8.2` and Java:
```
openjdk 22 2024-03-19
OpenJDK Runtime Environment GraalVM CE 22+36.1 (build 22+36-jvmci-b02)
OpenJDK 64-Bit Server VM GraalVM CE 22+36.1 (build 22+36-jvmci-b02, mixed mode, sharing)
```

**Comment by crimeminister** [comment]
I should mention, what resolved this issue for me was to exclude the dependency `com.google.protobuf/protobuf-java` when adding `jetcd` as a dependency.
