### ISSUE TITLE
SEVERE: [Channel<1>: (etcd)] Uncaught exception in the SynchronizationContext. Panic!

### ISSUE THREAD

**Issue by Liberxue** [etcd-io/jetcd#738]
```
SEVERE: [Channel<1>: (etcd)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.NoClassDefFoundError: io/grpc/internal/ManagedChannelImpl$SubchannelImpl$3
	at io.grpc.internal.ManagedChannelImpl$SubchannelImpl.shutdown(ManagedChannelImpl.java:1533)
	at io.grpc.internal.PickFirstLoadBalancer.shutdown(PickFirstLoadBalancer.java:113)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.shutdown(AutoConfiguredLoadBalancerFactory.java:181)
	at io.grpc.internal.ManagedChannelImpl.shutdownNameResolverAndLoadBalancer(ManagedChannelImpl.java:348)
	at io.grpc.internal.ManagedChannelImpl.enterIdleMode(ManagedChannelImpl.java:395)
	at io.grpc.internal.ManagedChannelImpl.access$900(ManagedChannelImpl.java:106)
	at io.grpc.internal.ManagedChannelImpl$IdleModeTimer.run(ManagedChannelImpl.java:326)
	at io.grpc.internal.Rescheduler$ChannelFutureRunnable.run(Rescheduler.java:103)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.Rescheduler$FutureRunnable.run(Rescheduler.java:80)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.grpc.internal.ManagedChannelImpl$SubchannelImpl$3
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:129)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more

Apr 15, 2020 8:21:39 AM io.grpc.internal.ManagedChannelImpl$1 uncaughtException
```

**Comment by lburgazzoli** [comment]
Please provide more details, this looks to me like a mixed version of grpc-java in the classpath but with the stack trace only I can't help much

**Comment by 809544928** [comment]
I meet the problem, can not fix it.
Yesterday I can run my code, but today it report this error.
