### ISSUE TITLE
jetcd tls error

### ISSUE THREAD

**Issue by hylitjob** [etcd-io/jetcd#748]
1. 证书生成步骤
```

`1. cfssl cfssljson 安装
curl -s -L -o /bin/cfssl https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
curl -s -L -o /bin/cfssljson https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
chmod +x /bin/cfssl*

2. 根秘钥生成
cfssl gencert -initca ca-csr.json | cfssljson -bare ca

3. etcd server端秘钥生成
cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=jpaas etcd-csr.json | cfssljson -bare etcd`
```
```
[root@shanghai-dev-12 etcd-v3.4.6-linux-amd64]# ls -l /etc/etcd/ssl
总用量 20
-rw-r--r--. 1 root root 1354 5月   6 02:43 ca.pem
-rw-r--r--. 1 root root 1070 5月   6 02:29 etcd.csr
-rw-r--r--. 1 root root  346 5月   6 02:29 etcd-csr.json
-rw-------. 1 root root 1679 5月   6 02:29 etcd-key.pem
-rw-r--r--. 1 root root 1436 5月   6 02:29 etcd.pem
```

1. java client代码
```
public class SslTest {

    private static final String DEFAULT_SSL_AUTHORITY = "SMZDM";
    private static final String DEFAULT_SSL_CA_PATH = "/Users/smzdm/Desktop/ca/etcd.pem";
    
    public static void main(String[] args) {
        ByteSequence key = ByteSequence.from("abc", StandardCharsets.UTF_8);
        ByteSequence val = ByteSequence.from("123", StandardCharsets.UTF_8);

        final String authority = System.getProperty("ssl.cert.authority", DEFAULT_SSL_AUTHORITY);

        try  {
            
           File is =  new File(DEFAULT_SSL_CA_PATH);
            
            Client client = Client.builder()
                    .endpoints("https://172.22.0.35:2379")
                    .authority(authority)
                    .sslContext(b -> b.trustManager(is))
                    .build();

            KV kv = client.getKVClient();
            kv.put(key, val).join();

            assertThat(kv.get(key).join().getCount()).isEqualTo(1);
            assertThat(kv.get(key).join().getKvs().get(0).getValue()).isEqualTo(val);

            kv.close();
            client.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

1. error info in console:

```
java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:607)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at net.jodah.failsafe.FailsafeFuture.completeResult(FailsafeFuture.java:90)
	at net.jodah.failsafe.AsyncExecution.complete(AsyncExecution.java:216)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at net.jodah.failsafe.RetryPolicyExecutor$1.lambda$null$0(RetryPolicyExecutor.java:113)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
	at net.jodah.failsafe.RetryPolicyExecutor$1.lambda$call$1(RetryPolicyExecutor.java:108)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at net.jodah.failsafe.Functions.lambda$null$2(Functions.java:107)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
	at net.jodah.failsafe.Functions.lambda$null$3(Functions.java:103)
	at net.jodah.failsafe.internal.util.DelegatingScheduler.lambda$schedule$0(DelegatingScheduler.java:141)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:533)
	at io.etcd.jetcd.ClientConnectionManager.lambda$execute$4(ClientConnectionManager.java:306)
	at net.jodah.failsafe.Functions.lambda$toCtxSupplier$15(Functions.java:276)
	at net.jodah.failsafe.Functions.lambda$getPromise$1(Functions.java:81)
	... 6 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:497)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.etcd.jetcd.ClientConnectionManager$AuthTokenInterceptor$1$1.onClose(ClientConnectionManager.java:336)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	... 3 more
Caused by: javax.net.ssl.SSLHandshakeException: error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:965)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1231)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1185)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1256)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1299)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:204)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1329)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

```

- error info in etcd log:

```
2020-05-07 15:13:01.823481 I | embed: rejected connection from "172.22.201.110:61787" (error "tls: client didn't provide a certificate", ServerName "")
2020-05-07 15:13:04.022462 I | embed: rejected connection from "172.22.201.110:61788" (error "tls: client didn't provide a certificate", ServerName "")
2020-05-07 15:13:08.550057 I | embed: rejected connection from "172.22.201.110:61789" (error "tls: client didn't provide a certificate", ServerName "")
2020-05-07 15:13:15.735867 I | embed: rejected connection from "172.22.201.110:61792" (error "tls: client didn't provide a certificate", ServerName "")
2020-05-07 15:13:26.563727 I | embed: rejected connection from "172.22.201.110:61801" (error "tls: client didn't provide a certificate", ServerName "")
2020-05-07 15:13:44.602394 I | embed: rejected connection from "172.22.201.110:61810" (error "tls: client didn't provide a certificate", ServerName "")
2020-05-07 15:19:46.199144 I | embed: rejected connection from "172.22.201.110:61965" (error "tls: client didn't provide a certificate", ServerName "")
2020-05-07 15:19:46.233660 I | embed: rejected connection from "172.22.201.110:61966" (error "tls: client didn't provide a certificate", ServerName "")
2020-05-07 15:19:47.627741 I | embed: rejected connection from "172.22.201.110:61967" (error "tls: client didn't provide a certificate", ServerName "")
2020-05-07 15:19:50.611353 I | embed: rejected connection from "172.22.201.110:61968" (error "tls: client didn't provide a certificate", ServerName "")
2020-05-07 15:19:54.745376 I | embed: rejected connection from "172.22.201.110:61971" (error "tls: client didn't provide a certificate", ServerName "")
2020-05-07 15:20:02.098699 I | embed: rejected connection from "172.22.201.110:61975" (error "tls: client didn't provide a certificate", ServerName "")
2020-05-07 15:20:13.989036 I | embed: rejected connection from "172.22.201.110:61977" (error "tls: client didn't provide a certificate", ServerName "")
2020-05-07 15:20:33.254420 I | embed: rejected connection from "172.22.201.110:61989" (error "tls: client didn't provide a certificate", ServerName "")
```

**Comment by hylitjob** [comment]
Test case shown below:

[https://github.com/etcd-io/jetcd/blob/master/jetcd-core/src/test/java/io/etcd/jetcd/SslTest.java](url)

**Comment by hylitjob** [comment]
It doesn't work, how to solve it?

**Comment by hylitjob** [comment]
fIXED

**Comment by fan10207** [comment]
> fIXED

how fixed it? the same error
