### ISSUE TITLE
The usage example is abnormal:NoClassDefFoundError: io/netty/channel/ChannelFactory

### ISSUE THREAD

**Issue by YouAnCao** [etcd-io/jetcd#826]
pom
```
        <dependency>
            <groupId>io.etcd</groupId>
            <artifactId>jetcd-core</artifactId>
            <version>0.5.3</version>
        </dependency>
```

code:
```
// create client
        Client client   = Client.builder().endpoints("http://localhost:2379").build();
        KV     kvClient = client.getKVClient();

        ByteSequence key   = ByteSequence.from("test_key".getBytes());
        ByteSequence value = ByteSequence.from("test_value".getBytes());

// put the key-value
        kvClient.put(key, value).get();

// get the CompletableFuture
        CompletableFuture<GetResponse> getFuture = kvClient.get(key);

// get the value from CompletableFuture
        GetResponse response = getFuture.get();

// delete the key
        kvClient.delete(key).get();
```

exception 
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/channel/ChannelFactory
	at io.etcd.jetcd.ClientConnectionManager.defaultChannelBuilder(ClientConnectionManager.java:202)
	at io.etcd.jetcd.ClientConnectionManager.getChannel(ClientConnectionManager.java:118)
	at io.etcd.jetcd.ClientImpl.<init>(ClientImpl.java:42)
	at io.etcd.jetcd.ClientBuilder.build(ClientBuilder.java:401)
	at Starter.main(Starter.java:17)
Caused by: java.lang.ClassNotFoundException: io.netty.channel.ChannelFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 5 more
```

**But it is normal to use version 0.0.2**

**Comment by lburgazzoli** [comment]
Can you check your dependency tree ?
Can you share a reproducer on github please?

**Comment by YouAnCao** [comment]
> Can you check your dependency tree ?
> Can you share a reproducer on github please?

thank you for your reply;
https://github.com/etcd-io/jetcd/issues/826#issuecomment-691966448
