### ISSUE TITLE
Unable to use TLS since 0.5.4

### ISSUE THREAD

**Issue by bh-tt** [etcd-io/jetcd#844]
We have an etcd cluster reachable using HTTPS. Since 0.5.4 we were unable to do this due to a TLS error. After some searching we found out jetcd no longer uses `https` schemes in its urls, instead opting for `ip` or `dns+srv`. This results in a target such as `ip:///etcd0.com:2379,etcd1.com:2379,etcd2.com:2379`. We have verified that the cluster is reachable using etcdctl. 

 - Should we simply disable TLS because jetcd uses a different scheme than HTTP?
- If not, how do we configure our certificates to work with the `ip` scheme? I cannot find anything online about this scheme.

## Reproduce
Try to connect to any etcd instance with the following SSLContext, using any common URI such as `https://etcd0.com:2379`:
```
import io.netty.handler.ssl.ApplicationProtocolConfig;
import io.netty.handler.ssl.SslContextBuilder;
                ApplicationProtocolConfig apn = new ApplicationProtocolConfig(
                        ApplicationProtocolConfig.Protocol.ALPN,
                        ApplicationProtocolConfig.SelectorFailureBehavior.NO_ADVERTISE,
                        ApplicationProtocolConfig.SelectedListenerFailureBehavior.ACCEPT,
                        "h2");
                builder = builder
                        .sslContext(SslContextBuilder
                                .forClient()
                                .applicationProtocolConfig(apn)
                                .build());
```

## Expected outcome
The jetcd client verifies the certificate correctly and connects to the etcd client

## Current outcome
```
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching ip found.
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:645)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:464)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
        at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1550)
        at io.netty.handler.ssl.SslHandler.access$1900(SslHandler.java:167)
        at io.netty.handler.ssl.SslHandler$SslTasksRunner.run(SslHandler.java:1737)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching ip found.
        at java.base/sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:212)
        at java.base/sun.security.util.HostnameChecker.match(HostnameChecker.java:103)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:429)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:283)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:623)
        ... 14 more
```

**Comment by bh-tt** [comment]
Using a no-op TrustManager that does not verification at all we can connect, but this is not desirable in a production setup.

**Comment by lburgazzoli** [comment]
We have this ssl tests that is currently working as expected: 

    https://github.com/etcd-io/jetcd/blob/master/jetcd-core/src/test/java/io/etcd/jetcd/SslTest.java

The fact that the uri scheme has changed does not affect of ssl is on or off. 
I guess you'd need to set the authority but mabe there is somethign missing.

Some help to set-up a test case would be really appreciated giving I don't have much time to work on jetcd.

**Comment by bh-tt** [comment]
I will take a look.

**Comment by bh-tt** [comment]
Setting authority works, thank you!

**Comment by Wang0310** [comment]
@bh-tt  How to set the authorization?

**Comment by bh-tt** [comment]
I set it using the builder method: `io.etcd.jetcd.Client.builder().authority("etcd");`

**Comment by Wang0310** [comment]
@bh-tt "etcd" is the value of hosts in the CA certificate issuing system.  
My code snippet:  
![image](https://user-images.githubusercontent.com/5894924/158546390-62ee8431-bc20-4cb9-b0ef-e2051ae87efa.png)
The etcd background log shows the following information:
Mar 16 16:18:44 localhost etcd: {"level":"warn","ts":"2022-03-16T16:18:44.483+0800","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"192.168.1.22:11385","server-name":"","error":"remote error: tls: internal error"}

so，So, I'm a little confused if it's my authorization setting or the code

**Comment by bh-tt** [comment]
Yes, the etcd server certificate has `etcd` as one of its SANs. I am using the `"h2"` String as supportedProtocols however, not HTTP_2. 

I do not use client certificate authorization, so I cannot help you with that.

**Comment by Wang0310** [comment]
Well, thank you anyway~
