### ISSUE TITLE
java.lang.NoSuchMethodError in ForwardingChannelBuilder.defaultChannelBuilder

### ISSUE THREAD

**Issue by Thomasdezeeuw** [etcd-io/jetcd#845]
I'm trying to port [YCSB](https://github.com/brianfrankcooper/YCSB) to etcd, with this library it's fairly easy. But I've hit the following error which I can't solve.

```log
Exception in thread "Thread-2" java.lang.NoSuchMethodError: 'io.grpc.ForwardingChannelBuilder io.grpc.netty.NettyChannelBuilder.defaultLoadBalancingPolicy(java.lang.String)'
	at io.etcd.jetcd.ClientConnectionManager.defaultChannelBuilder(ClientConnectionManager.java:260)
	at io.etcd.jetcd.ClientConnectionManager.defaultChannelBuilder(ClientConnectionManager.java:201)
	at io.etcd.jetcd.ClientConnectionManager.getChannel(ClientConnectionManager.java:123)
	at io.etcd.jetcd.ClientConnectionManager.newStub(ClientConnectionManager.java:172)
	at io.etcd.jetcd.KVImpl.<init>(KVImpl.java:54)
	at io.etcd.jetcd.ClientImpl.lambda$new$0(ClientImpl.java:38)
	at io.etcd.jetcd.support.MemoizingClientSupplier.get(MemoizingClientSupplier.java:37)
	at io.etcd.jetcd.ClientImpl.getKVClient(ClientImpl.java:55)
	at site.ycsb.db.EtcdClient.init(EtcdClient.java:39)
	at site.ycsb.DBWrapper.init(DBWrapper.java:86)
	at site.ycsb.ClientThread.run(ClientThread.java:91)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

On GitHub: https://github.com/etcd-io/jetcd/blob/18f20ee37dc1517b71460e4329391b9c32faa037/jetcd-core/src/main/java/io/etcd/jetcd/ClientConnectionManager.java#L260

My Java isn't the best any more, but `NettyChannelBuilder` inherits `defaultLoadBalancingPolicy` from `io.grpc.ForwardingChannelBuilder` according to its docs (https://grpc.github.io/grpc-java/javadoc/index.html?io/grpc/ForwardingChannelBuilder.html).

Any help would be appreciated.

**Comment by Thomasdezeeuw** [comment]
Relevant code is here: https://github.com/Thomasdezeeuw/YCSB/blob/cb239b8ddf900b3f59261de1d56ea78d31b582df/etcd/src/main/java/site/ycsb/db/EtcdClient.java.

**Comment by lburgazzoli** [comment]
This is usually caused by mixing version of netty/grpc can you check the version used by jetcd are not overridden by some of the project deps ?

**Comment by Thomasdezeeuw** [comment]
@lburgazzoli grpc-core and grpc-netty are both version 1.33.0, netty is 4.1.51.

```log
$ mvn -DskipTests clean dependency:tree -pl etcd

[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ etcd-binding ---
[INFO] site.ycsb:etcd-binding:jar:0.18.0-SNAPSHOT
[INFO] +- site.ycsb:core:jar:0.18.0-SNAPSHOT:provided
[INFO] |  +- org.apache.htrace:htrace-core4:jar:4.2.0-incubating:provided
[INFO] |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.4:provided
[INFO] |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.4:provided
[INFO] |  \- org.hdrhistogram:HdrHistogram:jar:2.1.12:provided
[INFO] +- io.etcd:jetcd-core:jar:0.5.4:compile
[INFO] |  +- io.etcd:jetcd-common:jar:0.5.4:compile
[INFO] |  |  \- com.google.guava:guava:jar:28.2-jre:compile
[INFO] |  |     +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |     +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |     +- org.checkerframework:checker-qual:jar:2.10.0:compile
[INFO] |  |     \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  +- io.grpc:grpc-core:jar:1.33.0:compile
[INFO] |  |  +- io.grpc:grpc-api:jar:1.33.0:compile (version selected from constraint [1.33.0,1.33.0])
[INFO] |  |  |  \- io.grpc:grpc-context:jar:1.33.0:compile
[INFO] |  |  +- com.google.code.gson:gson:jar:2.8.6:runtime
[INFO] |  |  +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |  |  +- org.codehaus.mojo:animal-sniffer-annotations:jar:1.18:runtime
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.3.4:compile
[INFO] |  |  +- io.perfmark:perfmark-api:jar:0.19.0:runtime
[INFO] |  |  \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- io.grpc:grpc-netty:jar:1.33.0:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.51.Final:compile
[INFO] |  |  |  +- io.netty:netty-common:jar:4.1.51.Final:compile
[INFO] |  |  |  +- io.netty:netty-buffer:jar:4.1.51.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport:jar:4.1.51.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-resolver:jar:4.1.51.Final:compile
[INFO] |  |  |  +- io.netty:netty-codec:jar:4.1.51.Final:compile
[INFO] |  |  |  +- io.netty:netty-handler:jar:4.1.51.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec-http:jar:4.1.51.Final:compile
[INFO] |  |  \- io.netty:netty-handler-proxy:jar:4.1.51.Final:runtime
[INFO] |  |     \- io.netty:netty-codec-socks:jar:4.1.51.Final:runtime
[INFO] |  +- io.grpc:grpc-protobuf:jar:1.33.0:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:3.12.0:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:1.17.0:compile
[INFO] |  |  \- io.grpc:grpc-protobuf-lite:jar:1.33.0:compile
[INFO] |  +- io.grpc:grpc-stub:jar:1.33.0:compile
[INFO] |  +- io.grpc:grpc-grpclb:jar:1.33.0:compile
[INFO] |  |  \- com.google.protobuf:protobuf-java-util:jar:3.12.0:runtime
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  +- net.jodah:failsafe:jar:2.4.0:compile
[INFO] |  \- com.google.auto.service:auto-service-annotations:jar:1.0-rc7:compile
[INFO] \- com.fasterxml.jackson.core:jackson-databind:jar:2.10.3:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.3:compile
[INFO]    \- com.fasterxml.jackson.core:jackson-core:jar:2.10.3:compile
```

But I think you're right about the dependencies, I got a couple of warnings about them. I'll look into it a bit more, thanks for the quick response.

**Comment by Thomasdezeeuw** [comment]
This seems to be a problem with the dependencies indeed, so I'm closing this. Thanks @lburgazzoli.
