### ISSUE TITLE
 Unexpected error occurred: cannot find a NameResolver for ip:///localhost:2379

### ISSUE THREAD

**Issue by marcosflobo** [etcd-io/jetcd#855]
Hello,

# Description
Playing with this project I've tried to do the hello world but unfortunately, the client code is not able to reach the etcd server (localhost)

```
Unexpected error occurred: cannot find a NameResolver for ip:///localhost:2379
```

It looks like my code is not able to reach the etcd server working as a Docker container when my local `etcdctl` actually can connect. I'm doing it all in localhost.

# How do I run the etcd server?
```
$ docker run -it --rm -p 2379:2379 -p 4001:4001 --name myetcd quay.io/coreos/etcd:v3.4.9 /usr/local/bin/etcd -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2020-11-25 10:47:39.497586 I | etcdmain: etcd Version: 3.4.9
2020-11-25 10:47:39.497648 I | etcdmain: Git SHA: 54ba95891
2020-11-25 10:47:39.497663 I | etcdmain: Go Version: go1.12.17
2020-11-25 10:47:39.497671 I | etcdmain: Go OS/Arch: linux/amd64
2020-11-25 10:47:39.497680 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2020-11-25 10:47:39.497694 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2020-11-25 10:47:39.499005 I | embed: name = default
2020-11-25 10:47:39.499025 I | embed: data dir = default.etcd
2020-11-25 10:47:39.499051 I | embed: member dir = default.etcd/member
2020-11-25 10:47:39.499070 I | embed: heartbeat = 100ms
2020-11-25 10:47:39.499089 I | embed: election = 1000ms
2020-11-25 10:47:39.499117 I | embed: snapshot count = 100000
2020-11-25 10:47:39.499143 I | embed: advertise client URLs = http://0.0.0.0:2379
2020-11-25 10:47:39.508815 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
raft2020/11/25 10:47:39 INFO: 8e9e05c52164694d switched to configuration voters=()
raft2020/11/25 10:47:39 INFO: 8e9e05c52164694d became follower at term 0
raft2020/11/25 10:47:39 INFO: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2020/11/25 10:47:39 INFO: 8e9e05c52164694d became follower at term 1
raft2020/11/25 10:47:39 INFO: 8e9e05c52164694d switched to configuration voters=(10276657743932975437)
2020-11-25 10:47:39.513242 W | auth: simple token is not cryptographically signed
2020-11-25 10:47:39.521558 I | etcdserver: starting server... [version: 3.4.9, cluster version: to_be_decided]
2020-11-25 10:47:39.522034 I | etcdserver: 8e9e05c52164694d as single-node; fast-forwarding 9 ticks (election ticks 10)
raft2020/11/25 10:47:39 INFO: 8e9e05c52164694d switched to configuration voters=(10276657743932975437)
2020-11-25 10:47:39.522848 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2020-11-25 10:47:39.524131 I | embed: listening for peers on 127.0.0.1:2380
raft2020/11/25 10:47:40 INFO: 8e9e05c52164694d is starting a new election at term 1
raft2020/11/25 10:47:40 INFO: 8e9e05c52164694d became candidate at term 2
raft2020/11/25 10:47:40 INFO: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2
raft2020/11/25 10:47:40 INFO: 8e9e05c52164694d became leader at term 2
raft2020/11/25 10:47:40 INFO: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2
2020-11-25 10:47:40.110936 I | etcdserver: setting up the initial cluster version to 3.4
2020-11-25 10:47:40.112290 N | etcdserver/membership: set the initial cluster version to 3.4
2020-11-25 10:47:40.112421 I | etcdserver/api: enabled capabilities for version 3.4
2020-11-25 10:47:40.112521 I | etcdserver: published {Name:default ClientURLs:[http://0.0.0.0:2379]} to cluster cdf818194e3a8c32
2020-11-25 10:47:40.112853 I | embed: ready to serve client requests
2020-11-25 10:47:40.114584 N | embed: serving insecure client requests on [::]:2379, this is strongly discouraged!
```
# Does the etcd work with the etcdctl?
Yes, 
```
$ etcdctl put foo bar --endpoints=localhost:2379
OK
$ etcdctl get foo --endpoints=192.168.1.43:2379
foo
bar
```

# The code I'm using
```
# MyController.java
...
Client client = Client.builder().endpoints("http://0.0.0.0:2379").build();
KV kvClient = client.getKVClient();
...
```

# What is the stack trace error
```
Unexpected error occurred: cannot find a NameResolver for ip:///0.0.0.0:2379
java.lang.IllegalArgumentException: cannot find a NameResolver for ip:///0.0.0.0:2379
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:744)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:633)
        at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:596)
        at io.grpc.ForwardingChannelBuilder.build(ForwardingChannelBuilder.java:255)
        at io.etcd.jetcd.ClientConnectionManager.getChannel(ClientConnectionManager.java:123)
        at io.etcd.jetcd.ClientConnectionManager.newStub(ClientConnectionManager.java:172)
        at io.etcd.jetcd.KVImpl.<init>(KVImpl.java:54)
        at io.etcd.jetcd.ClientImpl.lambda$new$0(ClientImpl.java:38)
        at io.etcd.jetcd.support.MemoizingClientSupplier.get(MemoizingClientSupplier.java:37)
        at io.etcd.jetcd.ClientImpl.getKVClient(ClientImpl.java:55)
        at com.marcosflobo.micronaut.etcd.demo.MyController.get(MyController.java:35)
```

# What else I've tried
- Instead of `http://localhost:2379`, I've tried with `http://0.0.0.0:2379`, `http://127.0.0.1:2379`, `http://$MYLOCALIP:2379`, `localhost:2379`

**Comment by lburgazzoli** [comment]
That seems quite strange as the resolver should be part of jetcd-core jar.
Can you share more info about the project set-up, dependencies etc ?

**Comment by marcosflobo** [comment]
Thanks for the fast response.

Yes, actually I continue investigating and I could reduce a bit the scope.

Actually, using directly the `jetcd` dependency, I do not face this error. This means that it works well in a clear Java Gradle app.

Now, I give you more context. I'm doing a wrapper/integration. I'm using `jetcd` on this micronaut integration (https://github.com/marcosflobo/micronaut-etcd/tree/feature/improve-interfaces). On that integration, all works well. But, when I create the fatJar of that integration, which contains the `jetcd` library too, is when I face this issue.

So
- From one side, the integration (https://github.com/marcosflobo/micronaut-etcd/tree/feature/improve-interfaces) where I import the `jetcd`
- From another side a dummy app (https://github.com/marcosflobo/micronaut-etcd-demo) to import the resultant fatJar of that integration

On the dummy app, is where I face this issue.

I've just uploaded all the code for both applications so you could reproduce it. Here the steps
1. Run local docker container for `etcd`
```
docker run -it --rm -p 2379:2379 -p 4001:4001 --name myetcd quay.io/coreos/etcd:v3.4.9 /usr/local/bin/etcd -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379
```
2. Clone the dummy app https://github.com/marcosflobo/micronaut-etcd-demo and run `./gradlew run` (it will run on localhost)
3. Perform a request to reproduce the issue
```
$ curl -X GET http://localhost:8080/v1/kv/foo --header "Content-Type: application/json"
```

And you will see on the run of the dummy app the full stack error like this:
```
15:55:22.474 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1562ms. Server Running: http://localhost:8080
15:55:28.505 [default-nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: cannot find a NameResolver for ip:///localhost:2379
java.lang.IllegalArgumentException: cannot find a NameResolver for ip:///localhost:2379
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:744)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:633)
        at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:596)
        at io.grpc.ForwardingChannelBuilder.build(ForwardingChannelBuilder.java:255)
        at io.etcd.jetcd.ClientConnectionManager.getChannel(ClientConnectionManager.java:123)
        at io.etcd.jetcd.ClientConnectionManager.newStub(ClientConnectionManager.java:172)
        at io.etcd.jetcd.KVImpl.<init>(KVImpl.java:54)
        at io.etcd.jetcd.ClientImpl.lambda$new$0(ClientImpl.java:38)
        at io.etcd.jetcd.support.MemoizingClientSupplier.get(MemoizingClientSupplier.java:37)
        at io.etcd.jetcd.ClientImpl.getKVClient(ClientImpl.java:55)
        at com.marcosflobo.micronaut.etcd.demo.MyController.get(MyController.java:24)
        at com.marcosflobo.micronaut.etcd.demo.$MyControllerDefinition$$exec1.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
        at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:469)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:312)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$10(RoutingInBoundHandler.java:1363)
        at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14868)
        at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.subscribe(WebMetricsPublisher.java:155)
        at io.micronaut.http.server.context.ServerRequestContextFilter.lambda$doFilter$0(ServerRequestContextFilter.java:62)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14868)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildExecutableRoute$6(RoutingInBoundHandler.java:1068)
        at io.micronaut.web.router.DefaultUriRouteMatch$1.execute(DefaultUriRouteMatch.java:80)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.handleRouteMatch(RoutingInBoundHandler.java:693)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:549)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:144)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:197)
        at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:121)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:205)
        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by lburgazzoli** [comment]
I think the problem is either in how the fat jar is created, so the relevant resources are not included or there is an issue with the classloader

**Comment by marcosflobo** [comment]
I think the same. However, it's strange to me that the way a JAR is created could affect a value is considered well or not. I'll keep investigating on the way the JAR is created? Any clue/advise?

Thanks!

**Comment by lburgazzoli** [comment]
it depends what shadow does, if it rename classes, then you also need to rename the service files

**Comment by lburgazzoli** [comment]
So I did test your demo and it works for me, at least it does not fail 
`compile files('tmplib/etcd-1.0.0.BUILD-SNAPSHOT-all.jar` however, looks suspicious as the `-all` is already an uber jar

**Comment by marcosflobo** [comment]
Did it work properly for you with no changes from the repo?

**Comment by lburgazzoli** [comment]
it does not build at all as it reference the `tmplib`
I got it working by changing to the real jetcd dependency, and by working it means it does not throw the exception you mentioned

**Comment by marcosflobo** [comment]
Indeed, using the real `jetcd` it works. I'll come back to this ASAP with a conclusion to my issue. What it's important is that the issue is not in the `jetcd` itself

**Comment by marcosflobo** [comment]
@lburgazzoli the problems as in my side, as you suspected ;). FYI Here the full topic and solution https://github.com/marcosflobo/micronaut-etcd/issues/9

Please, feel free to close this issue.

Thank you for your support!

**Comment by lburgazzoli** [comment]
ths for the feedback
