### ISSUE TITLE
Watch resume throw npe

### ISSUE THREAD

**Issue by kentchenjh** [etcd-io/jetcd#867]
**version**
0.5.0

**how to reproduce**
use a watch client and watch a event , then shut down etcd server, and wait for a min.

jetcd will throw a npe like this.
```
java.lang.NullPointerException: null  
	at io.etcd.jetcd.WatchImpl$WatcherImpl.onError(WatchImpl.java:262) ~[jetcd-core-0.5.0.jar:na]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449) ~[grpc-stub-1.27.1.jar:1.27.1]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-api-1.27.1.jar:1.27.1]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-api-1.27.1.jar:1.27.1]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-api-1.27.1.jar:1.27.1]
	at io.etcd.jetcd.ClientConnectionManager$AuthTokenInterceptor$1$1.onClose(ClientConnectionManager.java:289) ~[jetcd-core-0.5.0.jar:na]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) ~[grpc-core-1.27.1.jar:1.27.1]
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) ~[grpc-core-1.27.1.jar:1.27.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) ~[grpc-core-1.27.1.jar:1.27.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) ~[grpc-core-1.27.1.jar:1.27.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) ~[grpc-core-1.27.1.jar:1.27.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) ~[grpc-core-1.27.1.jar:1.27.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.27.1.jar:1.27.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.27.1.jar:1.27.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]
```

after that resuming watch is impossible.

**Comment by lburgazzoli** [comment]
can you test with latest release ?

**Comment by kentchenjh** [comment]
test with 0.5.3, no NPE show up, But watch is still unavailable after etcd server down for 2 or 3 mins. Is there any max retry time or timeout for watch?
