### ISSUE TITLE
Embrace gRPC deadlines

### ISSUE THREAD

**Issue by senfamulo** [etcd-io/jetcd#922]
Context:
In a 5 node production environment we encountered a situation where one of the nodes went completely crazy for yet uncertain reasons. It massively slowed down, gained seconds of clock difference and lost the connection to its peers. So far so bad, but the the quorum is not lost thus the system should keep on operating fine. However our client application instances use jetcd (0.5.0) to communicate with the cluster, with a round robbin strategy, so each client application sent requests also to this faulty node. What seemed to have happened, was that the faulty node was accepting all requests but answering none and soon all client applications were stuck with all their threads waiting for responses (and probably locks held by requesting threads? unfortunately no thread-dump was taken). So effectively a single node failure brought down our supposed-to-be highly available system.
Once the faulty node crashed completely minutes later, all the client applications threw loads of following exceptions and continued their work.
```
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
....
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:533)
	at io.etcd.jetcd.ClientConnectionManager.lambda$execute$4(ClientConnectionManager.java:331)
	at net.jodah.failsafe.Functions.lambda$toCtxSupplier$15(Functions.java:268)
	at net.jodah.failsafe.Functions.lambda$getPromise$1(Functions.java:80)
	at net.jodah.failsafe.RetryPolicyExecutor$1.call(RetryPolicyExecutor.java:101)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supplyAsync$1(RetryPolicyExecutor.java:139)
	at net.jodah.failsafe.Functions.lambda$null$3(Functions.java:97)
	at net.jodah.failsafe.internal.util.DelegatingScheduler.lambda$schedule$0(DelegatingScheduler.java:141)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 common frames omitted
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:497)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.etcd.jetcd.ClientConnectionManager$AuthTokenInterceptor$1$1.onClose(ClientConnectionManager.java:289)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	...
```

When realizing what probably happened, the next thought was _"isn't there some kind of timeout?"_. The naive assumption was, that jetcd can somehow handles such situations internally, as suggested by the [etcd guide](https://etcd.io/docs/v3.4/op-guide/failures/) regarding minor followers failure: _"Client libraries should hide these interruptions from users for read requests by automatically reconnecting to other members."_
As we could not find anything obvious regarding that in the jetcd API, we quickly ended up here: https://grpc.io/blog/deadlines/ - briefly _"TL;DR: Always set a deadline."_
There is only one use of a deadline in jetcd, in the `LeaseImpl`, which seems odd.
In search for a solution we found the `io.grpc.CallOptions` in the generated stubs but they are not easily accessable for our application code.
Following workaround using a `io.grpc.ClientInterceptor` seems to work, doing something like:
```
	return next.newCall(method, callOptions.withDeadline(Deadline.after(millis, TimeUnit.MILLISECONDS)));
```

But none of us is familiar with gRPC and the ramifications of such a solution. This also leaves us with the tricky part of how to handle retries in case a deadline is reached, which we are not sure yet if it can be done properly at the level of abstraction the interceptor lives on.

So to conclude, we do believe that jetcd is either in need of juggling deadlines internally or exposing an obvious and endorsed possibility to manage deadlines with reasonably safe defaults to prevent such disasters which we encountered.

What are your thoughts on this? Did we miss something obvious or can you confirm that this workaround is the best option we currently have to protect our system from such a situation?

Thanks and best regards!

**Comment by lburgazzoli** [comment]
I think a similar mechanic of what it is done in the lease client can be implemented in other part of the code, do you have any time to help on this feature ?

**Comment by senfamulo** [comment]
Thank you for the extraordinarily quick response!
I suppose the `io.etcd.jetcd.options.*` is a suitable place to give optional control over deadlines?
It would be my honor and pleasure to contribute, it's just that my employer would rather see me in prison than not owning every line of code i write or idea i have, be it in or off working hours :confounded: Well see what we can do...

**Comment by lburgazzoli** [comment]
io.etcd.jetcd.options.* seems fine but we can discuss while we iterate over the implementation.

looking forward to your contribution
